import pymel.core as pm
import Core_GMKRig.Utils as Utils
reload(Utils)

def KGM_CtrlAttrSet():
    #World 
    pm.setAttr("WorldCtrl.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("MoveCtrl.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("FlyCtrl.v",
        lock=True,channelBox=False,keyable=False)
    #//////////////////
    #Body
    #//////////////////
    #Body ctrl
    pm.setAttr("RootCtrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RootCtrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RootCtrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RootCtrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("HipIKCtrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("HipIKCtrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("HipIKCtrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("HipIKCtrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("BodyIKCtrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("BodyIKCtrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("BodyIKCtrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("BodyIKCtrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("SpineFK1Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineFK1Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineFK1Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineFK1Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("SpineFK2Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineFK2Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineFK2Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineFK2Ctrl.v",
        channelBox=True,keyable=False)
    #Body Sys
    pm.setAttr("SpineIKHandle.visibility",0)
    pm.setAttr("SpineIKHandle.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKCurve.visibility",0)
    pm.setAttr("SpineIKCurve.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKCurve.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKCurve.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKCurve.rx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKCurve.ry",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKCurve.rz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKCurve.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKCurve.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKCurve.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKCurve.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKChkCurve.visibility",0)
    pm.setAttr("SpineIKChkCurve.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKChkCurve.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKChkCurve.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKChkCurve.rx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKChkCurve.ry",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKChkCurve.rz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKChkCurve.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKChkCurve.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKChkCurve.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKChkCurve.v",
        lock=True,channelBox=False,keyable=False)
    #//////////////////
    #Neck
    #//////////////////
    pm.setAttr("HeadScaleConnectGrp.tx",
        lock=True)
    pm.setAttr("HeadScaleConnectGrp.ty",
        lock=True)
    pm.setAttr("HeadScaleConnectGrp.tz",
        lock=True)
    pm.setAttr("HeadScaleSquashGrp.tx",
        lock=True)
    pm.setAttr("HeadScaleSquashGrp.ty",
        lock=True)
    pm.setAttr("HeadScaleSquashGrp.tz",
        lock=True)
    pm.setAttr("HeadScaleSquashGrp.rx",
        lock=True)
    pm.setAttr("HeadScaleSquashGrp.ry",
        lock=True)
    pm.setAttr("HeadScaleSquashGrp.rz",
        lock=True)
    pm.setAttr("NeckCtrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("NeckCtrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("NeckCtrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("NeckCtrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("NeckCtrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("NeckCtrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("NeckCtrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("HeadCtrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("HeadCtrl.Neck",1)
    #Neck Sys
    pm.setAttr("NeckIKHandle.visibility",0)
    pm.setAttr("SpineIKHandle.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("NeckIKCurve.visibility",0)
    pm.setAttr("SpineIKCurve.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKCurve.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKCurve.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKCurve.rx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKCurve.ry",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKCurve.rz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKCurve.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKCurve.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKCurve.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKCurve.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("NeckIKChkCurve.visibility",0)
    pm.setAttr("SpineIKChkCurve.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKChkCurve.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKChkCurve.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKChkCurve.rx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKChkCurve.ry",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKChkCurve.rz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKChkCurve.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKChkCurve.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKChkCurve.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("SpineIKChkCurve.v",
        lock=True,channelBox=False,keyable=False)
    #//////////////////
    #Left Leg
    #//////////////////
    #Left Leg Fk
    pm.setAttr("LeftAnkleFKCtrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("LeftHipFKCtrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("LeftKneeFKCtrl.v",
        channelBox=True,keyable=False)
    #Left Leg Ik
    pm.setAttr("LeftLegIKHandle.visibility",0)
    pm.setAttr("LeftLegIKHandle.v",
        channelBox=True,keyable=False)
    pm.setAttr("LeftLegIKCtrl.v",
        channelBox=True,keyable=False)
    #Left Leg IKFK
    pm.setAttr("LeftLegIKFKCtrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftLegIKFKCtrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftLegIKFKCtrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftLegIKFKCtrl.rx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftLegIKFKCtrl.ry",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftLegIKFKCtrl.rz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftLegIKFKCtrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftLegIKFKCtrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftLegIKFKCtrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftLegIKFKCtrl.v",
        channelBox=True,keyable=False)
    #Left Leg Arc
    pm.setAttr("LeftLegDwArcIKHandle.visibility",0)
    pm.setAttr("LeftLegUpArcIKHandle.visibility",0)
    pm.setAttr("LeftLegDwArcIKHandle.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftLegUpArcIKHandle.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftLegDwArcChkCurve.visibility",0)
    pm.setAttr("LeftLegUpArcChkCurve.visibility",0)
    pm.setAttr("LeftLegDwArcChkCurve.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftLegUpArcChkCurve.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftLegDwArcCurve.visibility",0)
    pm.setAttr("LeftLegUpArcCurveOrig.visibility",0)
    pm.setAttr("LeftLegDWArcCurveOrig.visibility",0)
    pm.setAttr("LeftLegUpArcDetachCurve.visibility",0)
    pm.setAttr("LeftLegDwArcDetachCurve.visibility",0)
    pm.setAttr("LeftLegUpArcCurve.visibility",0)
    pm.setAttr("LeftLegDwArcCurve.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftLegUpArcCurveOrig.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftLegDWArcCurveOrig.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftLegUpArcDetachCurve.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftLegDwArcDetachCurve.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftLegUpArcCurve.v",
        lock=True,channelBox=False,keyable=False)
    #Left Foot
    pm.setAttr("LeftToeCtrlTarget.tx",
        lock=True)
    pm.setAttr("LeftToeCtrlTarget.ty",
        lock=True)
    pm.setAttr("LeftToeCtrlTarget.tz",
        lock=True)
    pm.setAttr("LeftToeCtrlTarget.rx",
        lock=True)
    pm.setAttr("LeftToeCtrlTarget.ry",
        lock=True)
    pm.setAttr("LeftToeCtrlTarget.rz",
        lock=True)
    pm.setAttr("LeftToeCtrlTarget.sx",
        lock=True)
    pm.setAttr("LeftToeCtrlTarget.sy",
        lock=True)
    pm.setAttr("LeftToeCtrlTarget.sz",
        lock=True)
    pm.setAttr("LeftAnkleFKCtrlTarget.tx",
        lock=True)
    pm.setAttr("LeftAnkleFKCtrlTarget.ty",
        lock=True)
    pm.setAttr("LeftAnkleFKCtrlTarget.tz",
        lock=True)
    pm.setAttr("LeftAnkleFKCtrlTarget.rx",
        lock=True)
    pm.setAttr("LeftAnkleFKCtrlTarget.ry",
        lock=True)
    pm.setAttr("LeftAnkleFKCtrlTarget.rz",
        lock=True)
    pm.setAttr("LeftAnkleFKCtrlTarget.sx",
        lock=True)
    pm.setAttr("LeftAnkleFKCtrlTarget.sy",
        lock=True)
    pm.setAttr("LeftAnkleFKCtrlTarget.sz",
        lock=True)
    pm.setAttr("LeftLegFootIKHandle.visibility",0)
    pm.setAttr("LeftLegFootIKHandle.v",
        lock=True)
    pm.setAttr("LeftLegToeIKHandle.visibility",0)
    pm.setAttr("LeftLegToeIKHandle.v",
        lock=True)
    pm.setAttr("LeftToeIKHandle.visibility",0)
    pm.setAttr("LeftToeIKHandle.v",
        lock=True)
    pm.setAttr("LeftToeCtrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftToeCtrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftToeCtrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftToeCtrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftToeCtrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftToeCtrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftToeCtrl.v",
        channelBox=True,keyable=False)
    #Left LegJnts
    pm.setAttr("LeftLegUpArcRig1Jnt.visibility",0)
    pm.setAttr("LeftLegRig1Jnt.visibility",0)
    pm.setAttr("LeftLegIK1Jnt.visibility",0)
    pm.setAttr("LeftLegFK1Jnt.visibility",0)
    pm.setAttr("LeftLegUpArcRig1Jnt.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftLegRig1Jnt.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftLegIK1Jnt.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftLegFK1Jnt.v",
        lock=True,channelBox=False,keyable=False)
    #Left Jnt Grp
    pm.setAttr("LeftLegRigJntGrp.visibility",0)
    pm.setAttr("LeftLegRigJntGrp.v",
        lock=True,channelBox=False,keyable=False)
    #Left toe
    pm.setAttr("LeftLegFootSystemJnt.visibility",0)
    pm.setAttr("LeftLegFootSystemJnt.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftToeLittle1RigJnt.visibility",0)
    pm.setAttr("LeftToeLittle1RigJnt.v",
        lock=True,channelBox=False,keyable=False)
    #//////////////////
    #Right Leg
    #//////////////////
    #Right Leg Fk
    pm.setAttr("RightAnkleFKCtrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("RightHipFKCtrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("RightKneeFKCtrl.v",
        channelBox=True,keyable=False)
    #Right Leg Ik
    pm.setAttr("RightLegIKHandle.visibility",0)
    pm.setAttr("RightLegIKHandle.v",
        channelBox=True,keyable=False)
    pm.setAttr("RightLegIKCtrl.v",
        channelBox=True,keyable=False)
    #Right Leg IKFK
    pm.setAttr("RightLegIKFKCtrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightLegIKFKCtrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightLegIKFKCtrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightLegIKFKCtrl.rx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightLegIKFKCtrl.ry",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightLegIKFKCtrl.rz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightLegIKFKCtrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightLegIKFKCtrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightLegIKFKCtrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightLegIKFKCtrl.v",
        channelBox=True,keyable=False)
    #Right Leg Arc
    pm.setAttr("RightLegDwArcIKHandle.visibility",0)
    pm.setAttr("RightLegUpArcIKHandle.visibility",0)
    pm.setAttr("RightLegDwArcIKHandle.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightLegUpArcIKHandle.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightLegDwArcChkCurve.visibility",0)
    pm.setAttr("RightLegUpArcChkCurve.visibility",0)
    pm.setAttr("RightLegDwArcChkCurve.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightLegUpArcChkCurve.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightLegDwArcCurve.visibility",0)
    pm.setAttr("RightLegUpArcCurveOrig.visibility",0)
    pm.setAttr("RightLegDWArcCurveOrig.visibility",0)
    pm.setAttr("RightLegUpArcDetachCurve.visibility",0)
    pm.setAttr("RightLegDwArcDetachCurve.visibility",0)
    pm.setAttr("RightLegUpArcCurve.visibility",0)
    pm.setAttr("RightLegDwArcCurve.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightLegUpArcCurveOrig.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightLegDWArcCurveOrig.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightLegUpArcDetachCurve.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightLegDwArcDetachCurve.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightLegUpArcCurve.v",
        lock=True,channelBox=False,keyable=False)
    #Right Foot
    pm.setAttr("RightToeCtrlTarget.tx",
        lock=True)
    pm.setAttr("RightToeCtrlTarget.ty",
        lock=True)
    pm.setAttr("RightToeCtrlTarget.tz",
        lock=True)
    pm.setAttr("RightToeCtrlTarget.rx",
        lock=True)
    pm.setAttr("RightToeCtrlTarget.ry",
        lock=True)
    pm.setAttr("RightToeCtrlTarget.rz",
        lock=True)
    pm.setAttr("RightToeCtrlTarget.sx",
        lock=True)
    pm.setAttr("RightToeCtrlTarget.sy",
        lock=True)
    pm.setAttr("RightToeCtrlTarget.sz",
        lock=True)
    pm.setAttr("RightAnkleFKCtrlTarget.tx",
        lock=True)
    pm.setAttr("RightAnkleFKCtrlTarget.ty",
        lock=True)
    pm.setAttr("RightAnkleFKCtrlTarget.tz",
        lock=True)
    pm.setAttr("RightAnkleFKCtrlTarget.rx",
        lock=True)
    pm.setAttr("RightAnkleFKCtrlTarget.ry",
        lock=True)
    pm.setAttr("RightAnkleFKCtrlTarget.rz",
        lock=True)
    pm.setAttr("RightAnkleFKCtrlTarget.sx",
        lock=True)
    pm.setAttr("RightAnkleFKCtrlTarget.sy",
        lock=True)
    pm.setAttr("RightAnkleFKCtrlTarget.sz",
        lock=True)
    pm.setAttr("RightLegFootIKHandle.visibility",0)
    pm.setAttr("RightLegFootIKHandle.v",
        lock=True)
    pm.setAttr("RightLegToeIKHandle.visibility",0)
    pm.setAttr("RightLegToeIKHandle.v",
        lock=True)
    pm.setAttr("RightToeIKHandle.visibility",0)
    pm.setAttr("RightToeIKHandle.v",
        lock=True)
    pm.setAttr("RightToeCtrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightToeCtrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightToeCtrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightToeCtrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightToeCtrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightToeCtrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightToeCtrl.v",
        channelBox=True,keyable=False)
    #Right LegJnts
    pm.setAttr("RightLegUpArcRig1Jnt.visibility",0)
    pm.setAttr("RightLegRig1Jnt.visibility",0)
    pm.setAttr("RightLegIK1Jnt.visibility",0)
    pm.setAttr("RightLegFK1Jnt.visibility",0)
    pm.setAttr("RightLegUpArcRig1Jnt.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightLegRig1Jnt.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightLegIK1Jnt.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightLegFK1Jnt.v",
        lock=True,channelBox=False,keyable=False)
    #Right Jnt Grp
    pm.setAttr("RightLegRigJntGrp.visibility",0)
    pm.setAttr("RightLegRigJntGrp.v",
        lock=True,channelBox=False,keyable=False)
    #Right toe
    pm.setAttr("RightLegFootSystemJnt.visibility",0)
    pm.setAttr("RightLegFootSystemJnt.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightToeLittle1RigJnt.visibility",0)
    pm.setAttr("RightToeLittle1RigJnt.v",
        lock=True,channelBox=False,keyable=False)
    #//////////////////
    #Left Arm
    #//////////////////
    #Left Clavicle
    pm.setAttr("LeftClavicleCtrl.v",
        channelBox=True,keyable=False)
    #Left Arm Fk
    pm.setAttr("LeftShoulderFKCtrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("LeftElbowFKCtrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("LeftWristFKCtrl.v",
        channelBox=True,keyable=False)
    #Left Arm Ik
    pm.setAttr("LeftArmIKHandle.visibility",0)
    pm.setAttr("LeftArmIKHandle.v",
        channelBox=True,keyable=False)
    pm.setAttr("LeftArmIKCtrl.v",
        channelBox=True,keyable=False)
    #Left Arm IKFK
    pm.setAttr("LeftArmIKFKCtrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftArmIKFKCtrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftArmIKFKCtrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftArmIKFKCtrl.rx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftArmIKFKCtrl.ry",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftArmIKFKCtrl.rz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftArmIKFKCtrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftArmIKFKCtrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftArmIKFKCtrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftArmIKFKCtrl.v",
        channelBox=True,keyable=False)
    #Left Arm Arc
    pm.setAttr("LeftArmDwArcIKHandle.visibility",0)
    pm.setAttr("LeftArmUpArcIKHandle.visibility",0)
    pm.setAttr("LeftArmDwArcIKHandle.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftArmUpArcIKHandle.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftArmDwArcChkCurve.visibility",0)
    pm.setAttr("LeftArmUpArcChkCurve.visibility",0)
    pm.setAttr("LeftArmDwArcChkCurve.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftArmUpArcChkCurve.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftArmDwArcCurve.visibility",0)
    pm.setAttr("LeftArmUpArcCurveOrig.visibility",0)
    pm.setAttr("LeftArmDWArcCurveOrig.visibility",0)
    pm.setAttr("LeftArmUpArcDetachCurve.visibility",0)
    pm.setAttr("LeftArmDwArcDetachCurve.visibility",0)
    pm.setAttr("LeftArmUpArcCurve.visibility",0)
    pm.setAttr("LeftArmDwArcCurve.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftArmUpArcCurveOrig.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftArmDWArcCurveOrig.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftArmUpArcDetachCurve.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftArmDwArcDetachCurve.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftArmUpArcCurve.v",
        lock=True,channelBox=False,keyable=False)
    #Left Hand
    pm.setAttr("LeftFingerPinkyIKCtrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerThumbIKCtrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerIndexIKCtrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerMiddleIKCtrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerRingIKCtrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerPinkyIKCtrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerThumbIKCtrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerIndexIKCtrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerMiddleIKCtrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerRingIKCtrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerPinkyIKCtrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerThumbIKCtrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerIndexIKCtrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerMiddleIKCtrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerRingIKCtrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerPinkyIKCtrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("LeftFingerThumbIKCtrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("LeftFingerIndexIKCtrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("LeftFingerMiddleIKCtrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("LeftFingerRingIKCtrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("LeftFingerCtrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerCtrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerCtrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerCtrl.rx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerCtrl.ry",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerCtrl.rz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerCtrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerCtrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerCtrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerCtrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("LeftFingerCtrl.IndexFold",
        lock=True)
    pm.setAttr("LeftFingerCtrl.MiddleFold",
        lock=True)
    pm.setAttr("LeftFingerCtrl.RingFold",
        lock=True)
    pm.setAttr("LeftFingerCtrl.PinkyFold",
        lock=True)
    pm.setAttr("LeftFingerCtrl.ThumbFold",
        lock=True)
    pm.setAttr("LeftFingerCtrl.Spread",
        lock=True)
    pm.setAttr("LeftFingerCtrl.Roll",
        lock=True)
    pm.setAttr("LeftFingerCtrl.MidIkCtrlVis",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerFKCtrlBase.visibility",0)
    pm.setAttr("LeftFingerFKCtrlBase.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerPinkyIKCtrl.ry",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerThumbIKCtrl.ry",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerIndexIKCtrl.ry",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerMiddleIKCtrl.ry",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerRingIKCtrl.ry",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerPinkyIKCtrl.rz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerThumbIKCtrl.rz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerIndexIKCtrl.rz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerMiddleIKCtrl.rz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerRingIKCtrl.rz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerPinky4Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerThumb1Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerThumb2Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerThumb3Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerThumb4Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerIndex1Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerIndex2Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerIndex3Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerIndex4Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerMiddle1Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerMiddle2Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerMiddle3Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerMiddle4Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerRing1Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerRing2Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerRing3Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerRing4Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerPinky1Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerPinky2Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerPinky3Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerPinky4Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerThumb1Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerThumb2Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerThumb3Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerThumb4Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerIndex1Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerIndex2Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerIndex3Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerIndex4Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerMiddle1Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerMiddle2Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerMiddle3Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerMiddle4Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerRing1Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerRing2Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerRing3Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerRing4Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerPinky1Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerPinky2Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerPinky3Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerPinky4Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerThumb1Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerThumb2Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerThumb3Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerThumb4Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerIndex1Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerIndex2Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerIndex3Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerIndex4Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerMiddle1Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerMiddle2Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerMiddle3Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerMiddle4Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerRing1Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerRing2Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerRing3Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerRing4Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerPinky1Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerPinky2Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerPinky3Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerPinky4Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerThumb1Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerThumb2Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerThumb3Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerThumb4Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerIndex1Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerIndex2Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerIndex3Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerIndex4Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerMiddle1Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerMiddle2Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerMiddle3Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerMiddle4Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerRing1Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerRing2Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerRing3Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerRing4Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerPinky1Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerPinky2Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerPinky3Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerPinky4Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerThumb1Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerThumb2Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerThumb3Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerThumb4Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerIndex1Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerIndex2Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerIndex3Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerIndex4Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerMiddle1Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerMiddle2Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerMiddle3Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerMiddle4Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerRing1Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerRing2Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerRing3Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerRing4Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerPinky1Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerPinky2Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerPinky3Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerPinky4Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerThumb1Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerThumb2Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerThumb3Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerThumb4Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerIndex1Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerIndex2Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerIndex3Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerIndex4Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerMiddle1Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerMiddle2Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerMiddle3Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerMiddle4Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerRing1Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerRing2Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerRing3Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerRing4Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerPinky1Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerPinky2Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerPinky3Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerPinky4Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("LeftFingerThumb1Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("LeftFingerThumb2Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("LeftFingerThumb3Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("LeftFingerThumb4Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("LeftFingerIndex1Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("LeftFingerIndex2Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("LeftFingerIndex3Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("LeftFingerIndex4Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("LeftFingerMiddle1Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("LeftFingerMiddle2Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("LeftFingerMiddle3Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("LeftFingerMiddle4Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("LeftFingerRing1Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("LeftFingerRing2Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("LeftFingerRing3Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("LeftFingerRing4Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("LeftFingerPinky1Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("LeftFingerPinky2Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("LeftFingerPinky3Ctrl.v",
        channelBox=True,keyable=False)
    #Left Arm Jnt
    pm.setAttr("LeftArmRigJntGrp.visibility",0)
    pm.setAttr("LeftArmRigJntGrp.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftArmUpArcRig1Jnt.visibility",0)
    pm.setAttr("LeftArmRig1Jnt.visibility",0)
    pm.setAttr("LeftArmIK1Jnt.visibility",0)
    pm.setAttr("LeftArmFK1Jnt.visibility",0)
    pm.setAttr("LeftArmUpArcRig1Jnt.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftArmRig1Jnt.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftArmIK1Jnt.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftArmFK1Jnt.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerCtrlJntGrp.visibility",0)
    pm.setAttr("LeftFingerCtrlJntGrp.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerPinky1RigJnt.visibility",0)
    pm.setAttr("LeftFingerThumb1RigJnt.visibility",0)
    pm.setAttr("LeftFingerIndex1RigJnt.visibility",0)
    pm.setAttr("LeftFingerMiddle1RigJnt.visibility",0)
    pm.setAttr("LeftFingerRing1RigJnt.visibility",0)
    pm.setAttr("LeftFingerPinky1RigJnt.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerThumb1RigJnt.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerIndex1RigJnt.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerMiddle1RigJnt.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftFingerRing1RigJnt.v",
        lock=True,channelBox=False,keyable=False)
    #//////////////////
    #Right Arm
    #//////////////////
    #Right Clavicle
    pm.setAttr("RightClavicleCtrl.v",
        channelBox=True,keyable=False)
    #Right Arm Fk
    pm.setAttr("RightShoulderFKCtrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("RightElbowFKCtrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("RightWristFKCtrl.v",
        channelBox=True,keyable=False)
    #Right Arm Ik
    pm.setAttr("RightArmIKHandle.visibility",0)
    pm.setAttr("RightArmIKHandle.v",
        channelBox=True,keyable=False)
    pm.setAttr("RightArmIKCtrl.v",
        channelBox=True,keyable=False)
    #Right Arm IKFK
    pm.setAttr("RightArmIKFKCtrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightArmIKFKCtrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightArmIKFKCtrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightArmIKFKCtrl.rx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightArmIKFKCtrl.ry",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightArmIKFKCtrl.rz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightArmIKFKCtrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightArmIKFKCtrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightArmIKFKCtrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightArmIKFKCtrl.v",
        channelBox=True,keyable=False)
    #Right Arm Arc
    pm.setAttr("RightArmDwArcIKHandle.visibility",0)
    pm.setAttr("RightArmUpArcIKHandle.visibility",0)
    pm.setAttr("RightArmDwArcIKHandle.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightArmUpArcIKHandle.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightArmDwArcChkCurve.visibility",0)
    pm.setAttr("RightArmUpArcChkCurve.visibility",0)
    pm.setAttr("RightArmDwArcChkCurve.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightArmUpArcChkCurve.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightArmDwArcCurve.visibility",0)
    pm.setAttr("RightArmUpArcCurveOrig.visibility",0)
    pm.setAttr("RightArmDWArcCurveOrig.visibility",0)
    pm.setAttr("RightArmUpArcDetachCurve.visibility",0)
    pm.setAttr("RightArmDwArcDetachCurve.visibility",0)
    pm.setAttr("RightArmUpArcCurve.visibility",0)
    pm.setAttr("RightArmDwArcCurve.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightArmUpArcCurveOrig.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightArmDWArcCurveOrig.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightArmUpArcDetachCurve.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightArmDwArcDetachCurve.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightArmUpArcCurve.v",
        lock=True,channelBox=False,keyable=False)
    #Right Hand
    pm.setAttr("RightFingerPinkyIKCtrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerThumbIKCtrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerIndexIKCtrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerMiddleIKCtrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerRingIKCtrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerPinkyIKCtrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerThumbIKCtrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerIndexIKCtrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerMiddleIKCtrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerRingIKCtrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerPinkyIKCtrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerThumbIKCtrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerIndexIKCtrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerMiddleIKCtrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerRingIKCtrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerPinkyIKCtrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("RightFingerThumbIKCtrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("RightFingerIndexIKCtrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("RightFingerMiddleIKCtrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("RightFingerRingIKCtrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("RightFingerCtrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerCtrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerCtrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerCtrl.rx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerCtrl.ry",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerCtrl.rz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerCtrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerCtrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerCtrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerCtrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("RightFingerCtrl.IndexFold",
        lock=True)
    pm.setAttr("RightFingerCtrl.MiddleFold",
        lock=True)
    pm.setAttr("RightFingerCtrl.RingFold",
        lock=True)
    pm.setAttr("RightFingerCtrl.PinkyFold",
        lock=True)
    pm.setAttr("RightFingerCtrl.ThumbFold",
        lock=True)
    pm.setAttr("RightFingerCtrl.Spread",
        lock=True)
    pm.setAttr("RightFingerCtrl.Roll",
        lock=True)
    pm.setAttr("RightFingerCtrl.MidIkCtrlVis",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerFKCtrlBase.visibility",0)
    pm.setAttr("RightFingerFKCtrlBase.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerPinkyIKCtrl.ry",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerThumbIKCtrl.ry",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerIndexIKCtrl.ry",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerMiddleIKCtrl.ry",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerRingIKCtrl.ry",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerPinkyIKCtrl.rz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerThumbIKCtrl.rz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerIndexIKCtrl.rz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerMiddleIKCtrl.rz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerRingIKCtrl.rz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerPinky4Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerThumb1Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerThumb2Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerThumb3Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerThumb4Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerIndex1Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerIndex2Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerIndex3Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerIndex4Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerMiddle1Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerMiddle2Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerMiddle3Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerMiddle4Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerRing1Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerRing2Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerRing3Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerRing4Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerPinky1Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerPinky2Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerPinky3Ctrl.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerPinky4Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerThumb1Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerThumb2Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerThumb3Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerThumb4Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerIndex1Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerIndex2Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerIndex3Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerIndex4Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerMiddle1Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerMiddle2Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerMiddle3Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerMiddle4Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerRing1Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerRing2Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerRing3Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerRing4Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerPinky1Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerPinky2Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerPinky3Ctrl.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerPinky4Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerThumb1Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerThumb2Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerThumb3Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerThumb4Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerIndex1Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerIndex2Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerIndex3Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerIndex4Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerMiddle1Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerMiddle2Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerMiddle3Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerMiddle4Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerRing1Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerRing2Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerRing3Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerRing4Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerPinky1Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerPinky2Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerPinky3Ctrl.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerPinky4Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerThumb1Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerThumb2Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerThumb3Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerThumb4Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerIndex1Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerIndex2Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerIndex3Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerIndex4Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerMiddle1Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerMiddle2Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerMiddle3Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerMiddle4Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerRing1Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerRing2Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerRing3Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerRing4Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerPinky1Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerPinky2Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerPinky3Ctrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerPinky4Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerThumb1Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerThumb2Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerThumb3Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerThumb4Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerIndex1Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerIndex2Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerIndex3Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerIndex4Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerMiddle1Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerMiddle2Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerMiddle3Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerMiddle4Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerRing1Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerRing2Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerRing3Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerRing4Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerPinky1Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerPinky2Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerPinky3Ctrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerPinky4Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerThumb1Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerThumb2Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerThumb3Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerThumb4Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerIndex1Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerIndex2Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerIndex3Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerIndex4Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerMiddle1Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerMiddle2Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerMiddle3Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerMiddle4Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerRing1Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerRing2Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerRing3Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerRing4Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerPinky1Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerPinky2Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerPinky3Ctrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerPinky4Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("RightFingerThumb1Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("RightFingerThumb2Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("RightFingerThumb3Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("RightFingerThumb4Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("RightFingerIndex1Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("RightFingerIndex2Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("RightFingerIndex3Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("RightFingerIndex4Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("RightFingerMiddle1Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("RightFingerMiddle2Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("RightFingerMiddle3Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("RightFingerMiddle4Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("RightFingerRing1Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("RightFingerRing2Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("RightFingerRing3Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("RightFingerRing4Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("RightFingerPinky1Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("RightFingerPinky2Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("RightFingerPinky3Ctrl.v",
        channelBox=True,keyable=False)
    #Right Arm Jnt
    pm.setAttr("RightArmRigJntGrp.visibility",0)
    pm.setAttr("RightArmRigJntGrp.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightArmUpArcRig1Jnt.visibility",0)
    pm.setAttr("RightArmRig1Jnt.visibility",0)
    pm.setAttr("RightArmIK1Jnt.visibility",0)
    pm.setAttr("RightArmFK1Jnt.visibility",0)
    pm.setAttr("RightArmUpArcRig1Jnt.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightArmRig1Jnt.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightArmIK1Jnt.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightArmFK1Jnt.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerCtrlJntGrp.visibility",0)
    pm.setAttr("RightFingerCtrlJntGrp.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerPinky1RigJnt.visibility",0)
    pm.setAttr("RightFingerThumb1RigJnt.visibility",0)
    pm.setAttr("RightFingerIndex1RigJnt.visibility",0)
    pm.setAttr("RightFingerMiddle1RigJnt.visibility",0)
    pm.setAttr("RightFingerRing1RigJnt.visibility",0)
    pm.setAttr("RightFingerPinky1RigJnt.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerThumb1RigJnt.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerIndex1RigJnt.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerMiddle1RigJnt.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightFingerRing1RigJnt.v",
        lock=True,channelBox=False,keyable=False)
    #eyes
    pm.setAttr("EyeCtrl.rx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("EyeCtrl.ry",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("EyeCtrl.rz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("EyeCtrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("EyeRollGrp.tx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("EyeRollGrp.ty",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("EyeRollGrp.tz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("EyeRollGrp.rx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("EyeRollGrp.ry",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("EyeRollGrp.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("EyeRollGrp.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("EyeRollGrp.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("EyeRollGrp.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightEyeCtrl.rx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftEyeCtrl.rx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightEyeCtrl.ry",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftEyeCtrl.ry",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightEyeCtrl.rz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftEyeCtrl.rz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightEyeCtrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftEyeCtrl.sx",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightEyeCtrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftEyeCtrl.sy",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightEyeCtrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftEyeCtrl.sz",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightEyeCtrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("LeftEyeCtrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("RightEyeIKHandle.visibility",0)
    pm.setAttr("LeftEyeIKHandle.visibility",0)
    pm.setAttr("RightEyeIKHandle.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftEyeIKHandle.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("RightEyeRigJnt.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("LeftEyeRigJnt.v",
        lock=True,channelBox=False,keyable=False)
    #oral
    pm.setAttr("JawCtrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("JawCtrl.TeethCtrlVis",
        channelBox=True,keyable=False)
    pm.setAttr("LowerTeethCtrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("UpperTeethCtrl.v",
        channelBox=True,keyable=False)
    #tongue
    pm.setAttr("TongueIKHandle.visibility",0)
    pm.setAttr("TongueIKHandle.v",
        lock=True)
    pm.setAttr("TongueIKChkCurve.visibility",0)
    pm.setAttr("TongueIKChkCurve.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("TongueIKCurve.visibility",0)
    pm.setAttr("TongueIKCurve.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("TongueRigSysGrp.visibility",0)
    pm.setAttr("TongueRigSysGrp.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("TongueIKRig1Jnt.visibility",1)
    pm.setAttr("TongueIKCtrlJnt.visibility",1)
    pm.setAttr("TongueIKRig1Jnt.visibility",0)
    pm.setAttr("TongueIKCtrlJnt.visibility",0)
    pm.setAttr("TongueIKRig1Jnt.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("TongueIKCtrlJnt.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("TongueIKCtrlEndJnt.visibility",0)
    pm.setAttr("TongueIKCtrlEndJnt.v",
        lock=True,channelBox=False,keyable=False)
    pm.setAttr("TongueCtrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("TongueIKCtrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("TongueFK3Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("TongueFK4Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("TongueFK5Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("TongueFK1Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("Tongue1Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("TongueFK2Ctrl.v",
        channelBox=True,keyable=False)
    pm.setAttr("Tongue2Ctrl.v",
        channelBox=True,keyable=False)
    


