import pymel.core as pm
import Core_GMKRig.Utils as Utils
reload(Utils)

def KGM_LeftLegArcSet():
    #/////////////////////////
    #Arc Joint 
    #/////////////////////////
    Utils.KGM_DuplicateJnt("LeftHipJnt", "LeftLegUpArcRig1Jnt")
    Utils.KGM_DuplicateJnt("LeftLegUpArc1Jnt", "LeftLegUpArcRig2Jnt")
    Utils.KGM_DuplicateJnt("LeftLegUpArc2Jnt", "LeftLegUpArcRig3Jnt")
    Utils.KGM_DuplicateJnt("LeftLegUpArc3Jnt", "LeftLegUpArcRig4Jnt")
    Utils.KGM_DuplicateJnt("LeftLegUpArc3Jnt", "LeftLegUpArcRig5Jnt")
    Utils.KGM_Aline("LeftKneeJnt", "LeftLegUpArcRig5Jnt", "p")
    Utils.KGM_DuplicateJnt("LeftKneeJnt", "LeftLegDwArcRig1Jnt")
    Utils.KGM_DuplicateJnt("LeftLegDwArc1Jnt", "LeftLegDwArcRig2Jnt")
    Utils.KGM_DuplicateJnt("LeftLegDwArc2Jnt", "LeftLegDwArcRig3Jnt")
    Utils.KGM_DuplicateJnt("LeftLegDwArc3Jnt", "LeftLegDwArcRig4Jnt")
    Utils.KGM_DuplicateJnt("LeftAnkleJnt", "LeftLegDwArcRig5Jnt")
    pm.parent('LeftLegDwArcRig5Jnt','LeftLegDwArcRig4Jnt')
    pm.parent('LeftLegDwArcRig4Jnt','LeftLegDwArcRig3Jnt')
    pm.parent('LeftLegDwArcRig3Jnt','LeftLegDwArcRig2Jnt')
    pm.parent('LeftLegDwArcRig2Jnt','LeftLegDwArcRig1Jnt')
    pm.parent('LeftLegDwArcRig1Jnt','LeftLegUpArcRig5Jnt')
    pm.parent('LeftLegUpArcRig5Jnt','LeftLegUpArcRig4Jnt')
    pm.parent('LeftLegUpArcRig4Jnt','LeftLegUpArcRig3Jnt')
    pm.parent('LeftLegUpArcRig3Jnt','LeftLegUpArcRig2Jnt')
    pm.parent('LeftLegUpArcRig2Jnt','LeftLegUpArcRig1Jnt')
    #/////////////////////////
    #Make Ctrls
    #/////////////////////////
    pm.curve(p=[(0, 1, 0), (0, 0, 0)],k=[0, 1],d=1)
    pm.rename("curve1","LeftLegUpArcCurveOrig")
    pm.curve(p=[(0, 1, 0), (0, 0, 0)],k=[0, 1],d=1)
    pm.rename("curve1","LeftLegDWArcCurveOrig")
    pm.curve(p=[(0, 1, 0), (0, 0, 0)],k=[0, 1],d=1)
    pm.rename("curve1","LeftLegUpArcDetachCurve")
    pm.curve(p=[(0, 1, 0), (0, 0, 0)],k=[0, 1],d=1)
    pm.rename("curve1","LeftLegDwArcDetachCurve")
    pm.curve(p=[(0, 1, 0), (0, 0, 0)],k=[0, 1],d=1)
    pm.rename("curve1","LeftLegUpArcCurve")
    pm.curve(p=[(0, 1, 0), (0, 0, 0)],k=[0, 1],d=1)
    pm.rename("curve1","LeftLegDwArcCurve")
    pm.group(em=1,n="LeftHipArcPoint")
    Utils.KGM_Aline("LeftLegRig1Jnt", "LeftHipArcPoint", "a")
    pm.group(em=1,n="LeftKneeArcPoint")
    Utils.KGM_Aline("LeftLegRig2Jnt", "LeftKneeArcPoint", "a")
    pm.group(em=1,n="LeftAnkleArcPoint")
    Utils.KGM_Aline("LeftLegRig3Jnt", "LeftAnkleArcPoint", "a")
    pm.group(em=1,n="LeftKneeArcCurvePoint")
    pm.group(em=1,n="LeftLegHipLockGrp")
    Utils.KGM_Aline("LeftHipJnt", "LeftLegHipLockGrp", "a")
    pm.group(em=1,n="LeftLegHipLockPoint")
    Utils.KGM_Aline("LeftLegUpArc1Jnt", "LeftLegHipLockPoint", "a")
    pm.group(em=1,n="LeftLegHipLockOrient")
    Utils.KGM_Aline("LeftHipJnt", "LeftLegHipLockOrient", "a")
    pm.parent('LeftLegHipLockPoint','LeftLegHipLockGrp')
    pm.parent('LeftLegHipLockOrient','LeftLegHipLockGrp')
    pm.group(em=1,n="LeftLegRigGrp")
    Utils.KGM_Aline("LeftLegRig1Jnt", "LeftLegRigGrp", "p")
    pm.parentConstraint('HipIKCtrl','LeftLegRigGrp',mo=1,weight=1,n="LeftLegRigGrpParCon")
    pm.parentConstraint('LeftLegRig1Jnt','LeftHipArcPoint',weight=1,n="LeftHipArcPointParentCon")
    pm.parentConstraint('LeftLegRig2Jnt','LeftKneeArcPoint',weight=1,n="LeftKneeArcPointParentCon")
    pm.parentConstraint('LeftLegRig3Jnt','LeftAnkleArcPoint',weight=1,n="LeftAnkleArcPointParentCon")
    pm.pointConstraint('LeftLegUpArcRig2Jnt','LeftLegHipLockPoint',mo=1,weight=1,n="LeftLegHipLockPointPointCon")
    pm.aimConstraint('LeftLegHipLockPoint','LeftLegHipLockOrient',weight=1,upVector=(0, 0, 1),
        n="LeftLegHipLockOrientAimCon",
        worldUpType="objectrotation",
        worldUpObject='LeftLegUpArcRig1Jnt',
        offset=(0, 0, 0),aimVector=(1, 0, 0),
        worldUpVector=(0, 0, 1))
    #////////////////////////////////////////////////////////////////////
    #Create Arc
    #////////////////////////////////////////////////////////////////////
    pm.connectAttr('LeftHipArcPoint.translate','LeftLegUpArcCurveOrigShape.controlPoints[0]',f=1)
    pm.connectAttr('LeftKneeArcPoint.translate','LeftLegUpArcCurveOrigShape.controlPoints[1]',f=1)
    pm.connectAttr('LeftKneeArcPoint.translate','LeftLegDWArcCurveOrigShape.controlPoints[0]',f=1)
    pm.connectAttr('LeftAnkleArcPoint.translate','LeftLegDWArcCurveOrigShape.controlPoints[1]',f=1)
    #
    pm.createNode('distanceBetween',n="LeftLegUpArcDis")
    pm.createNode('distanceBetween',n="LeftLegDwArcDis")
    pm.connectAttr('LeftHipArcPoint.translate','LeftLegUpArcDis.point1',f=1)
    pm.connectAttr('LeftKneeArcPoint.translate','LeftLegUpArcDis.point2',f=1)
    pm.connectAttr('LeftKneeArcPoint.translate','LeftLegDwArcDis.point1',f=1)
    pm.connectAttr('LeftAnkleArcPoint.translate','LeftLegDwArcDis.point2',f=1)
    # 
    pm.createNode('addDoubleLinear',n="LeftLegArcDisAdd")
    pm.connectAttr('LeftLegUpArcDis.distance','LeftLegArcDisAdd.input1',f=1)
    pm.connectAttr('LeftLegDwArcDis.distance','LeftLegArcDisAdd.input2',f=1)
    # 
    pm.createNode('multDoubleLinear',n="LeftLegArcDisMulti")
    pm.setAttr("LeftLegArcDisMulti.input2",3)
    pm.connectAttr('LeftLegArcDisAdd.output','LeftLegArcDisMulti.input1',f=1)
    # 
    pm.parentConstraint('LeftHipArcPoint','LeftKneeArcPoint','LeftAnkleArcPoint','LeftKneeArcCurvePoint',weight=1,n="LeftKneeArcCurvePointParentCon")
    pm.connectAttr('LeftLegDwArcDis.distance','LeftKneeArcCurvePointParentCon.LeftHipArcPointW0',f=1)
    pm.connectAttr('LeftLegArcDisMulti.output','LeftKneeArcCurvePointParentCon.LeftKneeArcPointW1',f=1)
    pm.connectAttr('LeftLegUpArcDis.distance','LeftKneeArcCurvePointParentCon.LeftAnkleArcPointW2',f=1)
    #
    pm.createNode('plusMinusAverage',n="LeftLegArcUpMinus")
    pm.setAttr('LeftLegArcUpMinus.operation',2)
    pm.connectAttr('LeftKneeArcCurvePoint.translate','LeftLegArcUpMinus.input3D[0]',f=1)
    pm.connectAttr('LeftHipArcPoint.translate','LeftLegArcUpMinus.input3D[1]',f=1)
    #
    pm.createNode('plusMinusAverage',n="LeftLegArcMinus")
    pm.setAttr('LeftLegArcMinus.operation',2)
    pm.connectAttr('LeftAnkleArcPoint.translate','LeftLegArcMinus.input3D[0]',f=1)
    pm.connectAttr('LeftHipArcPoint.translate','LeftLegArcMinus.input3D[1]',f=1)
    #
    pm.createNode('plusMinusAverage',n="LeftLegArcDwMinus")
    pm.setAttr('LeftLegArcDwMinus.operation',2)
    pm.connectAttr('LeftAnkleArcPoint.translate','LeftLegArcDwMinus.input3D[0]',f=1)
    pm.connectAttr('LeftKneeArcCurvePoint.translate','LeftLegArcDwMinus.input3D[1]',f=1)
    #
    pm.createNode('angleBetween',n="LeftLegArcUpAngle")
    pm.connectAttr('LeftLegArcUpMinus.output3D','LeftLegArcUpAngle.vector1',f=1)
    pm.connectAttr('LeftLegArcMinus.output3D','LeftLegArcUpAngle.vector2',f=1)
    #
    pm.createNode('angleBetween',n="LeftLegArcDwAngle")
    pm.connectAttr('LeftLegArcDwMinus.output3D','LeftLegArcDwAngle.vector1',f=1)
    pm.connectAttr('LeftLegArcMinus.output3D','LeftLegArcDwAngle.vector2',f=1)
    #
    pm.createNode('addDoubleLinear',n="LeftLegArcAngleAdd")
    pm.connectAttr('LeftLegArcUpAngle.angle','LeftLegArcAngleAdd.input1',f=1)
    pm.connectAttr('LeftLegArcDwAngle.angle','LeftLegArcAngleAdd.input2',f=1)
    #
    pm.createNode('makeThreePointCircularArc',n="LeftLegMakeCircularArc")
    pm.connectAttr('LeftHipArcPoint.translate','LeftLegMakeCircularArc.point1',f=1)
    pm.connectAttr('LeftKneeArcCurvePoint.translate','LeftLegMakeCircularArc.point2',f=1)
    pm.connectAttr('LeftAnkleArcPoint.translate','LeftLegMakeCircularArc.point3',f=1)
    pm.setAttr("LeftLegMakeCircularArc.sections",10)
    #
    pm.createNode('setRange',n="LeftLegArcSetRange")
    pm.connectAttr('LeftLegMakeCircularArc.sections','LeftLegArcSetRange.maxX',f=1)
    pm.connectAttr('LeftLegArcAngleAdd.output','LeftLegArcSetRange.oldMaxX',f=1)
    pm.connectAttr('LeftLegArcDwAngle.angle','LeftLegArcSetRange.valueX',f=1)
    #
    pm.createNode('detachCurve',n="LeftLegArcDetachCurve")
    pm.connectAttr('LeftLegMakeCircularArc.outputCurve','LeftLegArcDetachCurve.inputCurve',f=1)
    pm.connectAttr('LeftLegArcSetRange.outValueX','LeftLegArcDetachCurve.parameter[0]',f=1)
    # 
    pm.createNode('rebuildCurve',n="LeftLegUpRebuildCurve")
    pm.createNode('rebuildCurve',n="LeftLegDwRebuildCurve")
    pm.createNode('rebuildCurve',n="LeftLegUpArcRebuildCurve")
    pm.createNode('rebuildCurve',n="LeftLegDwArcRebuildCurve")
    pm.setAttr("LeftLegUpRebuildCurve.spans",2)
    pm.setAttr('LeftLegUpRebuildCurve.endKnots',1)
    pm.setAttr('LeftLegUpRebuildCurve.keepRange',0)
    pm.setAttr("LeftLegUpRebuildCurve.keepTangents",0)
    pm.setAttr("LeftLegDwRebuildCurve.spans",2)
    pm.setAttr('LeftLegDwRebuildCurve.endKnots',1)
    pm.setAttr('LeftLegDwRebuildCurve.keepRange',0)
    pm.setAttr("LeftLegDwRebuildCurve.keepTangents",0)
    pm.setAttr("LeftLegUpArcRebuildCurve.spans",2)
    pm.setAttr('LeftLegUpArcRebuildCurve.endKnots',1)
    pm.setAttr('LeftLegUpArcRebuildCurve.keepRange',0)
    pm.setAttr("LeftLegUpArcRebuildCurve.keepTangents",0)
    pm.setAttr("LeftLegDwArcRebuildCurve.spans",2)
    pm.setAttr('LeftLegDwArcRebuildCurve.endKnots',1)
    pm.setAttr('LeftLegDwArcRebuildCurve.keepRange',0)
    pm.setAttr("LeftLegDwArcRebuildCurve.keepTangents",0)
    pm.connectAttr('LeftLegUpArcCurveOrigShape.worldSpace[0]','LeftLegUpRebuildCurve.inputCurve',f=1)
    pm.connectAttr('LeftLegUpRebuildCurve.outputCurve','LeftLegUpArcCurveShape.create',f=1)
    pm.connectAttr('LeftLegDWArcCurveOrigShape.worldSpace[0]','LeftLegDwRebuildCurve.inputCurve',f=1)
    pm.connectAttr('LeftLegDwRebuildCurve.outputCurve','LeftLegDwArcCurveShape.create',f=1)
    pm.connectAttr('LeftLegArcDetachCurve.outputCurve[0]','LeftLegUpArcRebuildCurve.inputCurve',f=1)
    pm.connectAttr('LeftLegArcDetachCurve.outputCurve[1]','LeftLegDwArcRebuildCurve.inputCurve',f=1)
    pm.connectAttr('LeftLegUpArcRebuildCurve.outputCurve','LeftLegUpArcDetachCurveShape.create',f=1)
    pm.connectAttr('LeftLegDwArcRebuildCurve.outputCurve','LeftLegDwArcDetachCurveShape.create',f=1)
    pm.duplicate('LeftLegUpArcCurve',rr=1,n="LeftLegUpArcChkCurve")
    pm.duplicate('LeftLegDwArcCurve',rr=1,n="LeftLegDwArcChkCurve")
    #arcCurve blendShape
    pm.blendShape('LeftLegUpArcDetachCurve','LeftLegUpArcCurve',n="LeftLegUpArcBD")
    pm.rename("tweak1","LeftLegUpArcBDTweak")
    pm.blendShape('LeftLegDwArcDetachCurve','LeftLegDwArcCurve',n="LeftLegDwArcBD")
    pm.rename("tweak1","LeftLegDwArcBDTweak")
    pm.setAttr("LeftLegIKFKCtrl.Arc",10)
    pm.setAttr("LeftLegUpArcBD.LeftLegUpArcDetachCurve",1)
    pm.setAttr("LeftLegDwArcBD.LeftLegDwArcDetachCurve",1)
    pm.setDrivenKeyframe('LeftLegUpArcBD.LeftLegUpArcDetachCurve',currentDriver='LeftLegIKFKCtrl.Arc')
    pm.setDrivenKeyframe('LeftLegDwArcBD.LeftLegDwArcDetachCurve',currentDriver='LeftLegIKFKCtrl.Arc')
    pm.setAttr("LeftLegIKFKCtrl.Arc",0)
    pm.setAttr("LeftLegUpArcBD.LeftLegUpArcDetachCurve",0)
    pm.setAttr("LeftLegDwArcBD.LeftLegDwArcDetachCurve",0)
    pm.setDrivenKeyframe('LeftLegUpArcBD.LeftLegUpArcDetachCurve',currentDriver='LeftLegIKFKCtrl.Arc')
    pm.setDrivenKeyframe('LeftLegDwArcBD.LeftLegDwArcDetachCurve',currentDriver='LeftLegIKFKCtrl.Arc')
    #ik set
    pm.ikHandle(ccv=False,ee="LeftLegUpArcRig5Jnt",roc=False,curve="LeftLegUpArcCurve",sol='ikSplineSolver',sj="LeftLegUpArcRig1Jnt",ns=2)
    pm.rename("ikHandle1","LeftLegUpArcIKHandle")
    pm.rename("effector1","LeftLegUpArcEffector")
    pm.ikHandle(ccv=False,ee="LeftLegDwArcRig5Jnt",roc=False,curve="LeftLegDwArcCurve",sol='ikSplineSolver',sj="LeftLegDwArcRig1Jnt",ns=2)
    pm.rename("ikHandle1","LeftLegDwArcIKHandle")
    pm.rename("effector1","LeftLegDwArcEffector")
    pm.parent('LeftLegDwArcCurve',w=1)
    pm.setAttr("LeftLegUpArcIKHandle.rootOnCurve",1)
    pm.setAttr("LeftLegUpArcIKHandle.dTwistControlEnable",1)
    pm.setAttr('LeftLegUpArcIKHandle.dWorldUpType',4)
    pm.connectAttr('LeftHipTwistFix.worldMatrix[0]','LeftLegUpArcIKHandle.dWorldUpMatrix',f=1)
    pm.connectAttr('LeftKneeTwistFix.worldMatrix[0]','LeftLegUpArcIKHandle.dWorldUpMatrixEnd',f=1)
    pm.setAttr("LeftLegDwArcIKHandle.rootOnCurve",1)
    pm.setAttr("LeftLegDwArcIKHandle.dTwistControlEnable",1)
    pm.setAttr('LeftLegDwArcIKHandle.dWorldUpType',4)
    pm.connectAttr('LeftKneeTwistFix.worldMatrix[0]','LeftLegDwArcIKHandle.dWorldUpMatrix',f=1)
    pm.connectAttr('LeftAnkleTwistFix.worldMatrix[0]','LeftLegDwArcIKHandle.dWorldUpMatrixEnd',f=1)
    #///////////////////////////////////////////////////////////////
    #origein Leg Length
    #///////////////////////////////////////////////////////////////
    pm.createNode('pointOnCurveInfo',n="LeftLegUpArcChkCurvePoint1")
    pm.createNode('pointOnCurveInfo',n="LeftLegUpArcChkCurvePoint2")
    pm.createNode('pointOnCurveInfo',n="LeftLegUpArcChkCurvePoint3")
    pm.createNode('pointOnCurveInfo',n="LeftLegUpArcChkCurvePoint4")
    pm.createNode('pointOnCurveInfo',n="LeftLegUpArcChkCurvePoint5")
    pm.createNode('pointOnCurveInfo',n="LeftLegDwArcChkCurvePoint1")
    pm.createNode('pointOnCurveInfo',n="LeftLegDwArcChkCurvePoint2")
    pm.createNode('pointOnCurveInfo',n="LeftLegDwArcChkCurvePoint3")
    pm.createNode('pointOnCurveInfo',n="LeftLegDwArcChkCurvePoint4")
    pm.createNode('pointOnCurveInfo',n="LeftLegDwArcChkCurvePoint5")
    pm.connectAttr('LeftLegUpArcChkCurveShape.worldSpace[0]','LeftLegUpArcChkCurvePoint1.inputCurve',f=1)
    pm.connectAttr('LeftLegUpArcChkCurveShape.worldSpace[0]','LeftLegUpArcChkCurvePoint2.inputCurve',f=1)
    pm.connectAttr('LeftLegUpArcChkCurveShape.worldSpace[0]','LeftLegUpArcChkCurvePoint3.inputCurve',f=1)
    pm.connectAttr('LeftLegUpArcChkCurveShape.worldSpace[0]','LeftLegUpArcChkCurvePoint4.inputCurve',f=1)
    pm.connectAttr('LeftLegUpArcChkCurveShape.worldSpace[0]','LeftLegUpArcChkCurvePoint5.inputCurve',f=1)
    pm.setAttr("LeftLegUpArcChkCurvePoint1.parameter",0)
    pm.setAttr("LeftLegUpArcChkCurvePoint2.parameter",0.25)
    pm.setAttr("LeftLegUpArcChkCurvePoint3.parameter",0.5)
    pm.setAttr("LeftLegUpArcChkCurvePoint4.parameter",0.75)
    pm.setAttr("LeftLegUpArcChkCurvePoint5.parameter",1)
    pm.connectAttr('LeftLegDwArcChkCurveShape.worldSpace[0]','LeftLegDwArcChkCurvePoint1.inputCurve',f=1)
    pm.connectAttr('LeftLegDwArcChkCurveShape.worldSpace[0]','LeftLegDwArcChkCurvePoint2.inputCurve',f=1)
    pm.connectAttr('LeftLegDwArcChkCurveShape.worldSpace[0]','LeftLegDwArcChkCurvePoint3.inputCurve',f=1)
    pm.connectAttr('LeftLegDwArcChkCurveShape.worldSpace[0]','LeftLegDwArcChkCurvePoint4.inputCurve',f=1)
    pm.connectAttr('LeftLegDwArcChkCurveShape.worldSpace[0]','LeftLegDwArcChkCurvePoint5.inputCurve',f=1)
    pm.setAttr("LeftLegDwArcChkCurvePoint1.parameter",0)
    pm.setAttr("LeftLegDwArcChkCurvePoint2.parameter",0.25)
    pm.setAttr("LeftLegDwArcChkCurvePoint3.parameter",0.5)
    pm.setAttr("LeftLegDwArcChkCurvePoint4.parameter",0.75)
    pm.setAttr("LeftLegDwArcChkCurvePoint5.parameter",1)
    pm.createNode('distanceBetween',n="LeftLegUpArcChkCurveDis1")
    pm.createNode('distanceBetween',n="LeftLegUpArcChkCurveDis2")
    pm.createNode('distanceBetween',n="LeftLegUpArcChkCurveDis3")
    pm.createNode('distanceBetween',n="LeftLegUpArcChkCurveDis4")
    pm.createNode('distanceBetween',n="LeftLegDwArcChkCurveDis1")
    pm.createNode('distanceBetween',n="LeftLegDwArcChkCurveDis2")
    pm.createNode('distanceBetween',n="LeftLegDwArcChkCurveDis3")
    pm.createNode('distanceBetween',n="LeftLegDwArcChkCurveDis4")
    pm.connectAttr('LeftLegUpArcChkCurvePoint1.position','LeftLegUpArcChkCurveDis1.point1',f=1)
    pm.connectAttr('LeftLegUpArcChkCurvePoint2.position','LeftLegUpArcChkCurveDis1.point2',f=1)
    pm.connectAttr('LeftLegUpArcChkCurvePoint2.position','LeftLegUpArcChkCurveDis2.point1',f=1)
    pm.connectAttr('LeftLegUpArcChkCurvePoint3.position','LeftLegUpArcChkCurveDis2.point2',f=1)
    pm.connectAttr('LeftLegUpArcChkCurvePoint3.position','LeftLegUpArcChkCurveDis3.point1',f=1)
    pm.connectAttr('LeftLegUpArcChkCurvePoint4.position','LeftLegUpArcChkCurveDis3.point2',f=1)
    pm.connectAttr('LeftLegUpArcChkCurvePoint4.position','LeftLegUpArcChkCurveDis4.point1',f=1)
    pm.connectAttr('LeftLegUpArcChkCurvePoint5.position','LeftLegUpArcChkCurveDis4.point2',f=1)
    pm.connectAttr('LeftLegDwArcChkCurvePoint1.position','LeftLegDwArcChkCurveDis1.point1',f=1)
    pm.connectAttr('LeftLegDwArcChkCurvePoint2.position','LeftLegDwArcChkCurveDis1.point2',f=1)
    pm.connectAttr('LeftLegDwArcChkCurvePoint2.position','LeftLegDwArcChkCurveDis2.point1',f=1)
    pm.connectAttr('LeftLegDwArcChkCurvePoint3.position','LeftLegDwArcChkCurveDis2.point2',f=1)
    pm.connectAttr('LeftLegDwArcChkCurvePoint3.position','LeftLegDwArcChkCurveDis3.point1',f=1)
    pm.connectAttr('LeftLegDwArcChkCurvePoint4.position','LeftLegDwArcChkCurveDis3.point2',f=1)
    pm.connectAttr('LeftLegDwArcChkCurvePoint4.position','LeftLegDwArcChkCurveDis4.point1',f=1)
    pm.connectAttr('LeftLegDwArcChkCurvePoint5.position','LeftLegDwArcChkCurveDis4.point2',f=1)
    pm.createNode('plusMinusAverage',n="LeftLegUpArcChkDisPlus")
    pm.createNode('plusMinusAverage',n="LeftLegDwArcChkDisPlus")
    pm.connectAttr('LeftLegUpArcChkCurveDis1.distance','LeftLegUpArcChkDisPlus.input1D[0]',f=1)
    pm.connectAttr('LeftLegUpArcChkCurveDis2.distance','LeftLegUpArcChkDisPlus.input1D[1]',f=1)
    pm.connectAttr('LeftLegUpArcChkCurveDis3.distance','LeftLegUpArcChkDisPlus.input1D[2]',f=1)
    pm.connectAttr('LeftLegUpArcChkCurveDis4.distance','LeftLegUpArcChkDisPlus.input1D[3]',f=1)
    pm.connectAttr('LeftLegDwArcChkCurveDis1.distance','LeftLegDwArcChkDisPlus.input1D[0]',f=1)
    pm.connectAttr('LeftLegDwArcChkCurveDis2.distance','LeftLegDwArcChkDisPlus.input1D[1]',f=1)
    pm.connectAttr('LeftLegDwArcChkCurveDis3.distance','LeftLegDwArcChkDisPlus.input1D[2]',f=1)
    pm.connectAttr('LeftLegDwArcChkCurveDis4.distance','LeftLegDwArcChkDisPlus.input1D[3]',f=1)
    #////////////////////////////////////////////////////////////////
    # Arc Leg Length
    #////////////////////////////////////////////////////////////////
    pm.createNode('pointOnCurveInfo',n="LeftLegUpArcCurvePoint1")
    pm.createNode('pointOnCurveInfo',n="LeftLegUpArcCurvePoint2")
    pm.createNode('pointOnCurveInfo',n="LeftLegUpArcCurvePoint3")
    pm.createNode('pointOnCurveInfo',n="LeftLegUpArcCurvePoint4")
    pm.createNode('pointOnCurveInfo',n="LeftLegUpArcCurvePoint5")
    pm.createNode('pointOnCurveInfo',n="LeftLegDwArcCurvePoint1")
    pm.createNode('pointOnCurveInfo',n="LeftLegDwArcCurvePoint2")
    pm.createNode('pointOnCurveInfo',n="LeftLegDwArcCurvePoint3")
    pm.createNode('pointOnCurveInfo',n="LeftLegDwArcCurvePoint4")
    pm.createNode('pointOnCurveInfo',n="LeftLegDwArcCurvePoint5")
    pm.setAttr("LeftLegUpArcCurvePoint1.parameter",0)
    pm.setAttr("LeftLegUpArcCurvePoint2.parameter",0.25)
    pm.setAttr("LeftLegUpArcCurvePoint3.parameter",0.5)
    pm.setAttr("LeftLegUpArcCurvePoint4.parameter",0.75)
    pm.setAttr("LeftLegUpArcCurvePoint5.parameter",1)
    pm.setAttr("LeftLegDwArcCurvePoint1.parameter",0)
    pm.setAttr("LeftLegDwArcCurvePoint2.parameter",0.25)
    pm.setAttr("LeftLegDwArcCurvePoint3.parameter",0.5)
    pm.setAttr("LeftLegDwArcCurvePoint4.parameter",0.75)
    pm.setAttr("LeftLegDwArcCurvePoint5.parameter",1)
    pm.connectAttr('LeftLegUpArcCurveShape.worldSpace[0]','LeftLegUpArcCurvePoint1.inputCurve',f=1)
    pm.connectAttr('LeftLegUpArcCurveShape.worldSpace[0]','LeftLegUpArcCurvePoint2.inputCurve',f=1)
    pm.connectAttr('LeftLegUpArcCurveShape.worldSpace[0]','LeftLegUpArcCurvePoint3.inputCurve',f=1)
    pm.connectAttr('LeftLegUpArcCurveShape.worldSpace[0]','LeftLegUpArcCurvePoint4.inputCurve',f=1)
    pm.connectAttr('LeftLegUpArcCurveShape.worldSpace[0]','LeftLegUpArcCurvePoint5.inputCurve',f=1)
    pm.connectAttr('LeftLegDwArcCurveShape.worldSpace[0]','LeftLegDwArcCurvePoint1.inputCurve',f=1)
    pm.connectAttr('LeftLegDwArcCurveShape.worldSpace[0]','LeftLegDwArcCurvePoint2.inputCurve',f=1)
    pm.connectAttr('LeftLegDwArcCurveShape.worldSpace[0]','LeftLegDwArcCurvePoint3.inputCurve',f=1)
    pm.connectAttr('LeftLegDwArcCurveShape.worldSpace[0]','LeftLegDwArcCurvePoint4.inputCurve',f=1)
    pm.connectAttr('LeftLegDwArcCurveShape.worldSpace[0]','LeftLegDwArcCurvePoint5.inputCurve',f=1)
    pm.createNode('distanceBetween',n="LeftLegDwArcCurveDis1")
    pm.createNode('distanceBetween',n="LeftLegDwArcCurveDis2")
    pm.createNode('distanceBetween',n="LeftLegDwArcCurveDis3")
    pm.createNode('distanceBetween',n="LeftLegDwArcCurveDis4")
    pm.createNode('distanceBetween',n="LeftLegUpArcCurveDis1")
    pm.createNode('distanceBetween',n="LeftLegUpArcCurveDis2")
    pm.createNode('distanceBetween',n="LeftLegUpArcCurveDis3")
    pm.createNode('distanceBetween',n="LeftLegUpArcCurveDis4")
    pm.connectAttr('LeftLegUpArcCurvePoint1.position','LeftLegUpArcCurveDis1.point1',f=1)
    pm.connectAttr('LeftLegUpArcCurvePoint2.position','LeftLegUpArcCurveDis1.point2',f=1)
    pm.connectAttr('LeftLegUpArcCurvePoint2.position','LeftLegUpArcCurveDis2.point1',f=1)
    pm.connectAttr('LeftLegUpArcCurvePoint3.position','LeftLegUpArcCurveDis2.point2',f=1)
    pm.connectAttr('LeftLegUpArcCurvePoint3.position','LeftLegUpArcCurveDis3.point1',f=1)
    pm.connectAttr('LeftLegUpArcCurvePoint4.position','LeftLegUpArcCurveDis3.point2',f=1)
    pm.connectAttr('LeftLegUpArcCurvePoint4.position','LeftLegUpArcCurveDis4.point1',f=1)
    pm.connectAttr('LeftLegUpArcCurvePoint5.position','LeftLegUpArcCurveDis4.point2',f=1)
    pm.connectAttr('LeftLegDwArcCurvePoint1.position','LeftLegDwArcCurveDis1.point1',f=1)
    pm.connectAttr('LeftLegDwArcCurvePoint2.position','LeftLegDwArcCurveDis1.point2',f=1)
    pm.connectAttr('LeftLegDwArcCurvePoint2.position','LeftLegDwArcCurveDis2.point1',f=1)
    pm.connectAttr('LeftLegDwArcCurvePoint3.position','LeftLegDwArcCurveDis2.point2',f=1)
    pm.connectAttr('LeftLegDwArcCurvePoint3.position','LeftLegDwArcCurveDis3.point1',f=1)
    pm.connectAttr('LeftLegDwArcCurvePoint4.position','LeftLegDwArcCurveDis3.point2',f=1)
    pm.connectAttr('LeftLegDwArcCurvePoint4.position','LeftLegDwArcCurveDis4.point1',f=1)
    pm.connectAttr('LeftLegDwArcCurvePoint5.position','LeftLegDwArcCurveDis4.point2',f=1)
    pm.createNode('plusMinusAverage',n="LeftLegUpArcDisPlus")
    pm.createNode('plusMinusAverage',n="LeftLegDwArcDisPlus")
    pm.connectAttr('LeftLegUpArcCurveDis1.distance','LeftLegUpArcDisPlus.input1D[0]',f=1)
    pm.connectAttr('LeftLegUpArcCurveDis2.distance','LeftLegUpArcDisPlus.input1D[1]',f=1)
    pm.connectAttr('LeftLegUpArcCurveDis3.distance','LeftLegUpArcDisPlus.input1D[2]',f=1)
    pm.connectAttr('LeftLegUpArcCurveDis4.distance','LeftLegUpArcDisPlus.input1D[3]',f=1)
    pm.connectAttr('LeftLegDwArcCurveDis1.distance','LeftLegDwArcDisPlus.input1D[0]',f=1)
    pm.connectAttr('LeftLegDwArcCurveDis2.distance','LeftLegDwArcDisPlus.input1D[1]',f=1)
    pm.connectAttr('LeftLegDwArcCurveDis3.distance','LeftLegDwArcDisPlus.input1D[2]',f=1)
    pm.connectAttr('LeftLegDwArcCurveDis4.distance','LeftLegDwArcDisPlus.input1D[3]',f=1)
    #////////////////////////////////////////////////////////////////////////////
    #Arc/origin
    #////////////////////////////////////////////////////////////////////////////
    pm.createNode('multiplyDivide',n="LeftLegUpArcDisDivide")
    pm.createNode('multiplyDivide',n="LeftLegDwArcDisDivide")
    pm.setAttr('LeftLegUpArcDisDivide.operation',2)
    pm.setAttr('LeftLegDwArcDisDivide.operation',2)
    pm.connectAttr('LeftLegUpArcDisPlus.output1D','LeftLegUpArcDisDivide.input1X',f=1)
    pm.connectAttr('LeftLegUpArcChkDisPlus.output1D','LeftLegUpArcDisDivide.input2X',f=1)
    pm.connectAttr('LeftLegDwArcDisPlus.output1D','LeftLegDwArcDisDivide.input1X',f=1)
    pm.connectAttr('LeftLegDwArcChkDisPlus.output1D','LeftLegDwArcDisDivide.input2X',f=1)
    #setAttr "LeftKneeArcPointParentCon.target[0].targetOffsetTranslateZ" 0.001;
    #////////////////////////////////////////////////////////////////////////
    # joint tx
    #////////////////////////////////////////////////////////////////////////
    pm.createNode('multDoubleLinear',n="LeftLegUpArcTXMulti1")
    pm.setAttr("LeftLegUpArcTXMulti1.input2",
        pm.getAttr('LeftLegUpArcRig2Jnt.translateX'))
    pm.createNode('multDoubleLinear',n="LeftLegUpArcTXMulti2")
    pm.setAttr("LeftLegUpArcTXMulti2.input2",
        pm.getAttr('LeftLegUpArcRig3Jnt.translateX'))
    pm.createNode('multDoubleLinear',n="LeftLegUpArcTXMulti3")
    pm.setAttr("LeftLegUpArcTXMulti3.input2",
        pm.getAttr('LeftLegUpArcRig4Jnt.translateX'))
    pm.createNode('multDoubleLinear',n="LeftLegUpArcTXMulti4")
    pm.setAttr("LeftLegUpArcTXMulti4.input2",
        pm.getAttr('LeftLegUpArcRig5Jnt.translateX'))
    pm.connectAttr('LeftLegUpArcDisDivide.outputX','LeftLegUpArcTXMulti1.input1',f=1)
    pm.connectAttr('LeftLegUpArcDisDivide.outputX','LeftLegUpArcTXMulti2.input1',f=1)
    pm.connectAttr('LeftLegUpArcDisDivide.outputX','LeftLegUpArcTXMulti3.input1',f=1)
    pm.connectAttr('LeftLegUpArcDisDivide.outputX','LeftLegUpArcTXMulti4.input1',f=1)
    pm.connectAttr('LeftLegUpArcTXMulti1.output','LeftLegUpArcRig2Jnt.translateX',f=1)
    pm.connectAttr('LeftLegUpArcTXMulti2.output','LeftLegUpArcRig3Jnt.translateX',f=1)
    pm.connectAttr('LeftLegUpArcTXMulti3.output','LeftLegUpArcRig4Jnt.translateX',f=1)
    pm.connectAttr('LeftLegUpArcTXMulti4.output','LeftLegUpArcRig5Jnt.translateX',f=1)
    pm.createNode('multDoubleLinear',n="LeftLegDwArcTXMulti1")
    pm.setAttr("LeftLegDwArcTXMulti1.input2",
        pm.getAttr('LeftLegDwArcRig2Jnt.translateX'))
    pm.createNode('multDoubleLinear',n="LeftLegDwArcTXMulti2")
    pm.setAttr("LeftLegDwArcTXMulti2.input2",
        pm.getAttr('LeftLegDwArcRig3Jnt.translateX'))
    pm.createNode('multDoubleLinear',n="LeftLegDwArcTXMulti3")
    pm.setAttr("LeftLegDwArcTXMulti3.input2",
        pm.getAttr('LeftLegDwArcRig4Jnt.translateX'))
    pm.createNode('multDoubleLinear',n="LeftLegDwArcTXMulti4")
    pm.setAttr("LeftLegDwArcTXMulti4.input2",
        pm.getAttr('LeftLegDwArcRig5Jnt.translateX'))
    pm.connectAttr('LeftLegDwArcDisDivide.outputX','LeftLegDwArcTXMulti1.input1',f=1)
    pm.connectAttr('LeftLegDwArcDisDivide.outputX','LeftLegDwArcTXMulti2.input1',f=1)
    pm.connectAttr('LeftLegDwArcDisDivide.outputX','LeftLegDwArcTXMulti3.input1',f=1)
    pm.connectAttr('LeftLegDwArcDisDivide.outputX','LeftLegDwArcTXMulti4.input1',f=1)
    pm.connectAttr('LeftLegDwArcTXMulti1.output','LeftLegDwArcRig2Jnt.translateX',f=1)
    pm.connectAttr('LeftLegDwArcTXMulti2.output','LeftLegDwArcRig3Jnt.translateX',f=1)
    pm.connectAttr('LeftLegDwArcTXMulti3.output','LeftLegDwArcRig4Jnt.translateX',f=1)
    pm.connectAttr('LeftLegDwArcTXMulti4.output','LeftLegDwArcRig5Jnt.translateX',f=1)
    #///////////////////////////
    #outline
    #///////////////////////////
    pm.group(em=1,n="LeftLegArcRigGrp")
    Utils.KGM_Aline("LeftLegRig1Jnt", "LeftLegArcRigGrp", "p")
    pm.parent('LeftLegUpArcIKHandle','LeftLegArcRigGrp')
    pm.parent('LeftLegDwArcIKHandle','LeftLegArcRigGrp')
    pm.parent('LeftLegUpArcChkCurve','LeftLegArcRigGrp')
    pm.parent('LeftLegDwArcChkCurve','LeftLegArcRigGrp')
    pm.parent('LeftLegHipLockGrp','LeftLegArcRigGrp')
    pm.parent('LeftLegUpArcRig1Jnt','LeftLegRigJntGrp')
    pm.group(em=1,n="LeftLegRigCtrlGrp")
    Utils.KGM_Aline("LeftLegRig1Jnt", "LeftLegRigCtrlGrp", "p")
    pm.parent('LeftLegIKGrp','LeftLegRigCtrlGrp')
    pm.parent('LeftLegFKGrp','LeftLegRigCtrlGrp')
    pm.parent('LeftLegIKFKCtrlGrp','LeftLegRigCtrlGrp')
    pm.parent('LeftLegArcRigGrp','LeftLegRigCtrlGrp')
    pm.parent('LeftLegRigJntGrp','LeftLegRigCtrlGrp')
    pm.parent('LeftLegRigGrp','RigCtrlGrp')
    pm.parent('LeftLegRigCtrlGrp','LeftLegRigGrp')
    pm.group(em=1,n="LeftLegArcGrp")
    pm.parent('LeftHipArcPoint','LeftLegArcGrp')
    pm.parent('LeftKneeArcPoint','LeftLegArcGrp')
    pm.parent('LeftAnkleArcPoint','LeftLegArcGrp')
    pm.parent('LeftKneeArcCurvePoint','LeftLegArcGrp')
    pm.parent('LeftLegUpArcCurveOrig','LeftLegArcGrp')
    pm.parent('LeftLegDWArcCurveOrig','LeftLegArcGrp')
    pm.parent('LeftLegUpArcDetachCurve','LeftLegArcGrp')
    pm.parent('LeftLegDwArcDetachCurve','LeftLegArcGrp')
    pm.parent('LeftLegUpArcCurve','LeftLegArcGrp')
    pm.parent('LeftLegDwArcCurve','LeftLegArcGrp')
    pm.parent('LeftLegArcGrp','LeftLegRigSysGrp')
    pm.reorder('LeftLegRig1Jnt',relative=-2)
    pm.reorder('LeftLegIK1Jnt',relative=-1)
    pm.reorder('LeftLegUpArcRig1Jnt',relative=-1)
    