import pymel.core as pm
import Core_GMKRig.Utils as Utils
reload(Utils)

def KGM_RightLegConnectSet():
    pm.parentConstraint('RightLegHipLockOrient','RightHipJnt',mo=1,weight=1,n="RightHipJntParentCon")
    #RightHipJnt
    #RightLegUpArc1Jnt
    pm.parentConstraint('RightLegUpArcRig2Jnt','RightLegUpArc1Jnt',mo=1,weight=1,n="RightLegUpArc1JntParentCon")
    # RightLegUpArc2Jnt
    pm.pointConstraint('RightLegUpArcRig3Jnt','RightLegUpArc2Jnt',mo=1,weight=1,n="RightLegUpArc2JntPointCon")
    pm.createNode('multiplyDivide',n="RightLegUpArcRig3JntRotateMulti")
    pm.setAttr("RightLegUpArcRig3JntRotateMulti.input2X",-1)
    pm.setAttr("RightLegUpArcRig3JntRotateMulti.input2Y",1)
    pm.setAttr("RightLegUpArcRig3JntRotateMulti.input2Z",-1)
    pm.connectAttr('RightLegUpArcRig3Jnt.rotate','RightLegUpArcRig3JntRotateMulti.input1',f=1)
    pm.connectAttr('RightLegUpArcRig3JntRotateMulti.output','RightLegUpArc2Jnt.rotate',f=1)
    # RightLegUpArc3Jnt
    pm.pointConstraint('RightLegUpArcRig4Jnt','RightLegUpArc3Jnt',mo=1,weight=1,n="RightLegUpArc3JntPointCon")
    pm.createNode('multiplyDivide',n="RightLegUpArcRig4JntRotateMulti")
    pm.setAttr("RightLegUpArcRig4JntRotateMulti.input2X",-1)
    pm.setAttr("RightLegUpArcRig4JntRotateMulti.input2Y",1)
    pm.setAttr("RightLegUpArcRig4JntRotateMulti.input2Z",-1)
    pm.connectAttr('RightLegUpArcRig4Jnt.rotate','RightLegUpArcRig4JntRotateMulti.input1',f=1)
    pm.connectAttr('RightLegUpArcRig4JntRotateMulti.output','RightLegUpArc3Jnt.rotate',f=1)
    #RightKneeJnt
    pm.pointConstraint('RightLegDwArcRig1Jnt','RightKneeJnt',mo=1,weight=1,n="RightKneeJntPointCon")
    pm.createNode('multiplyDivide',n="RightLegDwArcRig1JntRotateMulti")
    pm.setAttr("RightLegDwArcRig1JntRotateMulti.input2X",-1)
    pm.setAttr("RightLegDwArcRig1JntRotateMulti.input2Y",1)
    pm.setAttr("RightLegDwArcRig1JntRotateMulti.input2Z",-1)
    pm.connectAttr('RightLegDwArcRig1Jnt.rotate','RightLegDwArcRig1JntRotateMulti.input1',f=1)
    pm.connectAttr('RightLegDwArcRig1JntRotateMulti.output','RightKneeJnt.rotate',f=1)
    #RightLegDwArc1Jnt
    pm.pointConstraint('RightLegDwArcRig2Jnt','RightLegDwArc1Jnt',mo=1,weight=1,n="RightLegDwArc1JntPointCon")
    pm.createNode('multiplyDivide',n="RightLegDwArcRig2JntRotateMulti")
    pm.setAttr("RightLegDwArcRig2JntRotateMulti.input2X",-1)
    pm.setAttr("RightLegDwArcRig2JntRotateMulti.input2Y",1)
    pm.setAttr("RightLegDwArcRig2JntRotateMulti.input2Z",-1)
    pm.connectAttr('RightLegDwArcRig2Jnt.rotate','RightLegDwArcRig2JntRotateMulti.input1',f=1)
    pm.connectAttr('RightLegDwArcRig2JntRotateMulti.output','RightLegDwArc1Jnt.rotate',f=1)
    #RightLegDwArc2Jnt
    pm.pointConstraint('RightLegDwArcRig3Jnt','RightLegDwArc2Jnt',mo=1,weight=1,n="RightLegDwArc2JntPointCon")
    pm.createNode('multiplyDivide',n="RightLegDwArcRig3JntRotateMulti")
    pm.setAttr("RightLegDwArcRig3JntRotateMulti.input2X",-1)
    pm.setAttr("RightLegDwArcRig3JntRotateMulti.input2Y",1)
    pm.setAttr("RightLegDwArcRig3JntRotateMulti.input2Z",-1)
    pm.connectAttr('RightLegDwArcRig3Jnt.rotate','RightLegDwArcRig3JntRotateMulti.input1',f=1)
    pm.connectAttr('RightLegDwArcRig3JntRotateMulti.output','RightLegDwArc2Jnt.rotate',f=1)
    #RightLegDwArc3Jnt
    pm.pointConstraint('RightLegDwArcRig4Jnt','RightLegDwArc3Jnt',mo=1,weight=1,n="RightLegDwArc3JntPointCon")
    pm.createNode('multiplyDivide',n="RightLegDwArcRig4JntRotateMulti")
    pm.setAttr("RightLegDwArcRig4JntRotateMulti.input2X",-1)
    pm.setAttr("RightLegDwArcRig4JntRotateMulti.input2Y",1)
    pm.setAttr("RightLegDwArcRig4JntRotateMulti.input2Z",-1)
    pm.connectAttr('RightLegDwArcRig4Jnt.rotate','RightLegDwArcRig4JntRotateMulti.input1',f=1)
    pm.connectAttr('RightLegDwArcRig4JntRotateMulti.output','RightLegDwArc3Jnt.rotate',f=1)
    #RightAnkleFKConnectGrp
    pm.pointConstraint('RightLegRig3Jnt','RightAnkleFKConnectGrp',mo=1,weight=1,n="RightAnkleFKConnectGrpPointCon")
    pm.orientConstraint('RightLegRig3Jnt','RightAnkleFKConnectGrp',mo=1,weight=1,n="RightAnkleFKConnectGrpOrientCon")
    #RightAnkleJnt
    pm.parentConstraint('RightLegFootSystemJnt','RightAnkleJnt',mo=1,weight=1,n="RightAnkleJntParCon")
    #RightBallJnt
    pm.parentConstraint('RightToeCtrl','RightBallJnt',mo=1,weight=1,n="RightBallJntParCon")
    #///////////////////////////
    #Scale blend
    #///////////////////////////
    #RightHipIKFKScaleBlend
    pm.createNode('blendColors',n="RightHipIKFKScaleBlend")
    pm.connectAttr('RightLegIKFKCtrl.IKFK','RightHipIKFKScaleBlend.blender',f=1)
    pm.connectAttr('RightLegFK1Jnt.scale','RightHipIKFKScaleBlend.color1',f=1)
    pm.connectAttr('RightLegIK1Jnt.scale','RightHipIKFKScaleBlend.color2',f=1)
    #RightHipJnt
    pm.connectAttr('RightHipIKFKScaleBlend.outputG','RightHipJnt.scaleY',f=1)
    pm.connectAttr('RightHipIKFKScaleBlend.outputB','RightHipJnt.scaleZ',f=1)
    #RightLegUpArc1Jnt
    pm.connectAttr('RightHipIKFKScaleBlend.outputG','RightLegUpArc1Jnt.scaleY',f=1)
    pm.connectAttr('RightHipIKFKScaleBlend.outputB','RightLegUpArc1Jnt.scaleZ',f=1)
    #RightLegUpArc2Jnt
    pm.connectAttr('RightHipIKFKScaleBlend.outputG','RightLegUpArc2Jnt.scaleY',f=1)
    pm.connectAttr('RightHipIKFKScaleBlend.outputB','RightLegUpArc2Jnt.scaleZ',f=1)
    #RightLegUpArc3Jnt
    pm.connectAttr('RightHipIKFKScaleBlend.outputG','RightLegUpArc3Jnt.scaleY',f=1)
    pm.connectAttr('RightHipIKFKScaleBlend.outputB','RightLegUpArc3Jnt.scaleZ',f=1)
    #RightKneeIKFKScaleBlend
    pm.createNode('blendColors',n="RightKneeIKFKScaleBlend")
    pm.connectAttr('RightLegIKFKCtrl.IKFK','RightKneeIKFKScaleBlend.blender',f=1)
    pm.connectAttr('RightLegFK2Jnt.scale','RightHipIKFKScaleBlend.color1',f=1)
    pm.connectAttr('RightLegIK2Jnt.scale','RightHipIKFKScaleBlend.color2',f=1)
    #RightKneeJnt
    pm.connectAttr('RightHipIKFKScaleBlend.outputG','RightKneeJnt.scaleY',f=1)
    pm.connectAttr('RightHipIKFKScaleBlend.outputB','RightKneeJnt.scaleZ',f=1)
    #RightLegDwArc1Jnt
    pm.connectAttr('RightHipIKFKScaleBlend.outputG','RightLegDwArc1Jnt.scaleY',f=1)
    pm.connectAttr('RightHipIKFKScaleBlend.outputB','RightLegDwArc1Jnt.scaleZ',f=1)
    #RightLegDwArc2Jnt
    pm.connectAttr('RightHipIKFKScaleBlend.outputG','RightLegDwArc2Jnt.scaleY',f=1)
    pm.connectAttr('RightHipIKFKScaleBlend.outputB','RightLegDwArc2Jnt.scaleZ',f=1)
    #RightLegDwArc3Jnt
    pm.connectAttr('RightHipIKFKScaleBlend.outputG','RightLegDwArc3Jnt.scaleY',f=1)
    pm.connectAttr('RightHipIKFKScaleBlend.outputB','RightLegDwArc3Jnt.scaleZ',f=1)
    #RightAnkleFKScaleBlend
    pm.createNode('blendColors',n="RightAnkleFKScaleBlend")
    pm.setAttr("RightAnkleFKScaleBlend.color2R",1)
    pm.setAttr("RightAnkleFKScaleBlend.color2G",1)
    pm.setAttr("RightAnkleFKScaleBlend.color2B",1)
    pm.connectAttr('RightLegIKFKCtrl.IKFK','RightAnkleFKScaleBlend.blender',f=1)
    pm.connectAttr('RightAnkleFKCtrl.scale','RightAnkleFKScaleBlend.color1',f=1)
    #RightAnkleFKConnectGrp
    pm.connectAttr('RightAnkleFKScaleBlend.output','RightAnkleFKConnectGrp.scale',f=1)
    #RightToeCtrlGrp
    pm.connectAttr('RightAnkleFKScaleBlend.output','RightToeCtrlGrp.scale',f=1)
    #RightAnkleIKConnectGrp
    pm.createNode('blendColors',n="RightAnkleIKScaleBlend")
    pm.setAttr("RightAnkleIKScaleBlend.color1R",1)
    pm.setAttr("RightAnkleIKScaleBlend.color1G",1)
    pm.setAttr("RightAnkleIKScaleBlend.color1B",1)
    pm.connectAttr('RightLegIKFKCtrl.IKFK','RightAnkleIKScaleBlend.blender',f=1)
    pm.connectAttr('RightLegIKCtrl.scale','RightAnkleIKScaleBlend.color2',f=1)
    #RightAnkleIKConnectGrp
    pm.connectAttr('RightAnkleIKScaleBlend.output','RightAnkleIKConnectGrp.scale',f=1)
    #RightToeCtrlIKScaleGrp
    pm.connectAttr('RightAnkleIKScaleBlend.output','RightToeCtrlIKScaleGrp.scale',f=1)
    


