import pymel.core as pm
import Core_GMKRig.Utils as Utils
reload(Utils)

def KGM_TongueSet():
    #/////////////////////////
    #make rig Jnt
    #/////////////////////////
    pm.select(cl=1)
    pm.joint(p=(0, 0, 0),n="TongueIKCtrlEndJnt")
    Utils.KGM_Aline("Tongue6Jnt", "TongueIKCtrlEndJnt", "p")
    pm.select(cl=1)
    pm.joint(p=(0, 0, 0),n="TongueIKCtrlJnt")
    Utils.KGM_Aline("Tongue1Jnt", "TongueIKCtrlJnt", "p")
    Utils.KGM_DuplicateJnt("Tongue1Jnt", "TongueIKRig1Jnt")
    Utils.KGM_DuplicateJnt("Tongue2Jnt", "TongueIKRig2Jnt")
    Utils.KGM_DuplicateJnt("Tongue3Jnt", "TongueIKRig3Jnt")
    Utils.KGM_DuplicateJnt("Tongue4Jnt", "TongueIKRig4Jnt")
    Utils.KGM_DuplicateJnt("Tongue5Jnt", "TongueIKRig5Jnt")
    Utils.KGM_DuplicateJnt("Tongue6Jnt", "TongueIKRig6Jnt")
    pm.parent('TongueIKRig6Jnt','TongueIKRig5Jnt')
    pm.parent('TongueIKRig5Jnt','TongueIKRig4Jnt')
    pm.parent('TongueIKRig4Jnt','TongueIKRig3Jnt')
    pm.parent('TongueIKRig3Jnt','TongueIKRig2Jnt')
    pm.parent('TongueIKRig2Jnt','TongueIKRig1Jnt')
    pm.setAttr("TongueIKCtrlJnt.radius",0.1)
    pm.setAttr("TongueIKCtrlEndJnt.radius",0.1)
    pm.setAttr("TongueIKRig6Jnt.radius",0.1)
    pm.setAttr("TongueIKRig1Jnt.radius",0.1)
    pm.setAttr("TongueIKRig2Jnt.radius",0.1)
    pm.setAttr("TongueIKRig3Jnt.radius",0.1)
    pm.setAttr("TongueIKRig4Jnt.radius",0.1)
    pm.setAttr("TongueIKRig5Jnt.radius",0.1)
    #/////////////////////////
    #make ctrl
    #/////////////////////////
    pm.curve(p=[(-0.111731, 0, -0.0419849), (-0.111731, 0, 0.0419849), (0.111731, 0, 0.0419849), (0.111731, 0, -0.0419849), (-0.111731, 0, -0.0419849)],k=[0, 1, 2, 3, 4],d=1)
    pm.delete(ch=1)
    pm.rename("curve1","TongueCtrl")
    Utils.KGM_MakeCtrlShape("TongueCtrl")
    pm.curve(p=[(0, 0.131452, 0), (0, 0, 0.131452), (0, -0.131452, 0), (0, 0, -0.131452), (0, 0.131452, 0)],k=[0, 1, 2, 3, 4],d=1)
    pm.delete(ch=1)
    pm.rename("curve1","TongueFK1Ctrl")
    Utils.KGM_MakeCtrlShape("TongueFK1Ctrl")
    pm.curve(p=[(0, 0.131452, 0), (0, 0, 0.131452), (0, -0.131452, 0), (0, 0, -0.131452), (0, 0.131452, 0)],k=[0, 1, 2, 3, 4],d=1)
    pm.delete(ch=1)
    pm.rename("curve1","TongueFK2Ctrl")
    pm.group('TongueFK2Ctrl',n="TongueFK2CtrlGrp")
    pm.curve(p=[(0, 0.131452, 0), (0, 0, 0.131452), (0, -0.131452, 0), (0, 0, -0.131452), (0, 0.131452, 0)],k=[0, 1, 2, 3, 4],d=1)
    pm.delete(ch=1)
    pm.rename("curve1","TongueFK3Ctrl")
    pm.group('TongueFK3Ctrl',n="TongueFK3CtrlGrp")
    pm.curve(p=[(0, 0.131452, 0), (0, 0, 0.131452), (0, -0.131452, 0), (0, 0, -0.131452), (0, 0.131452, 0)],k=[0, 1, 2, 3, 4],d=1)
    pm.delete(ch=1)
    pm.rename("curve1","TongueFK4Ctrl")
    pm.group('TongueFK4Ctrl',n="TongueFK4CtrlGrp")
    pm.curve(p=[(0, 0.131452, 0), (0, 0, 0.131452), (0, -0.131452, 0), (0, 0, -0.131452), (0, 0.131452, 0)],k=[0, 1, 2, 3, 4],d=1)
    pm.delete(ch=1)
    pm.rename("curve1","TongueFK5Ctrl")
    pm.group('TongueFK5Ctrl',n="TongueFK5CtrlGrp")
    pm.curve(p=[(0, 0.089834, 0), (0, 0, 0.089834), (0, -0.089834, 0), (0, 0, -0.089834), (0, 0.089834, 0)],k=[0, 1, 2, 3, 4],d=1)
    pm.delete(ch=1)
    pm.rename("curve1","Tongue1Ctrl")
    Utils.KGM_MakeCtrlShape("Tongue1Ctrl")
    pm.curve(p=[(0, 0.089834, 0), (0, 0, 0.089834), (0, -0.089834, 0), (0, 0, -0.089834), (0, 0.089834, 0)],k=[0, 1, 2, 3, 4],d=1)
    pm.delete(ch=1)
    pm.rename("curve1","Tongue2Ctrl")
    pm.curve(p=[(0, 0.089834, 0), (0, 0, 0.089834), (0, -0.089834, 0), (0, 0, -0.089834), (0, 0.089834, 0)],k=[0, 1, 2, 3, 4],d=1)
    pm.delete(ch=1)
    pm.rename("curve1","Tongue3Ctrl")
    pm.curve(p=[(0, 0.089834, 0), (0, 0, 0.089834), (0, -0.089834, 0), (0, 0, -0.089834), (0, 0.089834, 0)],k=[0, 1, 2, 3, 4],d=1)
    pm.delete(ch=1)
    pm.rename("curve1","Tongue4Ctrl")
    pm.curve(p=[(0, 0.128248, 0.0427492), (0, 0.0427492, 0.0427492), (0, 0.0427492, 0.128248), (0, -0.0427492, 0.128248), (0, -0.0427492, 0.0427492), (0, -0.128248, 0.0427492), (0, -0.128248, -0.0427492), (0, -0.0427492, -0.0427492), (0, -0.0427492, -0.128248), (0, 0.0427492, -0.128248), (0, 0.0427492, -0.0427492), (0, 0.128248, -0.0427492), (0, 0.128248, 0.0427492)],k=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],d=1)
    pm.delete(ch=1)
    pm.rename("curve1","TongueIKCtrl")
    Utils.KGM_MakeCtrlShape("TongueIKCtrl")
    pm.duplicate('TongueFK1CtrlBaseCurveInfo',rr=1,n="TongueFK2CtrlBaseCurveInfo ")
    pm.duplicate('TongueFK1CtrlBaseCurveInfo',rr=1,n="TongueFK3CtrlBaseCurveInfo ")
    pm.duplicate('TongueFK1CtrlBaseCurveInfo',rr=1,n="TongueFK4CtrlBaseCurveInfo ")
    pm.duplicate('TongueFK1CtrlBaseCurveInfo',rr=1,n="TongueFK5CtrlBaseCurveInfo ")
    pm.connectAttr('TongueFK1CtrlBaseShape.worldSpace[0]','TongueFK2CtrlBaseCurveInfo.inputCurve',f=1)
    pm.connectAttr('TongueFK1CtrlBaseShape.worldSpace[0]','TongueFK3CtrlBaseCurveInfo.inputCurve',f=1)
    pm.connectAttr('TongueFK1CtrlBaseShape.worldSpace[0]','TongueFK4CtrlBaseCurveInfo.inputCurve',f=1)
    pm.connectAttr('TongueFK1CtrlBaseShape.worldSpace[0]','TongueFK5CtrlBaseCurveInfo.inputCurve',f=1)
    pm.connectAttr('TongueFK2CtrlBaseCurveInfo.controlPoints[0]','TongueFK2CtrlShape.controlPoints[0]',f=1)
    pm.connectAttr('TongueFK2CtrlBaseCurveInfo.controlPoints[1]','TongueFK2CtrlShape.controlPoints[1]',f=1)
    pm.connectAttr('TongueFK2CtrlBaseCurveInfo.controlPoints[2]','TongueFK2CtrlShape.controlPoints[2]',f=1)
    pm.connectAttr('TongueFK2CtrlBaseCurveInfo.controlPoints[3]','TongueFK2CtrlShape.controlPoints[3]',f=1)
    pm.connectAttr('TongueFK2CtrlBaseCurveInfo.controlPoints[4]','TongueFK2CtrlShape.controlPoints[4]',f=1)
    pm.connectAttr('TongueFK3CtrlBaseCurveInfo.controlPoints[0]','TongueFK3CtrlShape.controlPoints[0]',f=1)
    pm.connectAttr('TongueFK3CtrlBaseCurveInfo.controlPoints[1]','TongueFK3CtrlShape.controlPoints[1]',f=1)
    pm.connectAttr('TongueFK3CtrlBaseCurveInfo.controlPoints[2]','TongueFK3CtrlShape.controlPoints[2]',f=1)
    pm.connectAttr('TongueFK3CtrlBaseCurveInfo.controlPoints[3]','TongueFK3CtrlShape.controlPoints[3]',f=1)
    pm.connectAttr('TongueFK3CtrlBaseCurveInfo.controlPoints[4]','TongueFK3CtrlShape.controlPoints[4]',f=1)
    pm.connectAttr('TongueFK4CtrlBaseCurveInfo.controlPoints[0]','TongueFK4CtrlShape.controlPoints[0]',f=1)
    pm.connectAttr('TongueFK4CtrlBaseCurveInfo.controlPoints[1]','TongueFK4CtrlShape.controlPoints[1]',f=1)
    pm.connectAttr('TongueFK4CtrlBaseCurveInfo.controlPoints[2]','TongueFK4CtrlShape.controlPoints[2]',f=1)
    pm.connectAttr('TongueFK4CtrlBaseCurveInfo.controlPoints[3]','TongueFK4CtrlShape.controlPoints[3]',f=1)
    pm.connectAttr('TongueFK4CtrlBaseCurveInfo.controlPoints[4]','TongueFK4CtrlShape.controlPoints[4]',f=1)
    pm.connectAttr('TongueFK5CtrlBaseCurveInfo.controlPoints[0]','TongueFK5CtrlShape.controlPoints[0]',f=1)
    pm.connectAttr('TongueFK5CtrlBaseCurveInfo.controlPoints[1]','TongueFK5CtrlShape.controlPoints[1]',f=1)
    pm.connectAttr('TongueFK5CtrlBaseCurveInfo.controlPoints[2]','TongueFK5CtrlShape.controlPoints[2]',f=1)
    pm.connectAttr('TongueFK5CtrlBaseCurveInfo.controlPoints[3]','TongueFK5CtrlShape.controlPoints[3]',f=1)
    pm.connectAttr('TongueFK5CtrlBaseCurveInfo.controlPoints[4]','TongueFK5CtrlShape.controlPoints[4]',f=1)
    pm.duplicate('Tongue1CtrlBaseCurveInfo',rr=1,n="Tongue2CtrlBaseCurveInfo ")
    pm.duplicate('Tongue1CtrlBaseCurveInfo',rr=1,n="Tongue3CtrlBaseCurveInfo ")
    pm.duplicate('Tongue1CtrlBaseCurveInfo',rr=1,n="Tongue4CtrlBaseCurveInfo ")
    pm.connectAttr('Tongue1CtrlBaseCurveInfo.controlPoints[0]','Tongue2CtrlShape.controlPoints[0]',f=1)
    pm.connectAttr('Tongue1CtrlBaseCurveInfo.controlPoints[1]','Tongue2CtrlShape.controlPoints[1]',f=1)
    pm.connectAttr('Tongue1CtrlBaseCurveInfo.controlPoints[2]','Tongue2CtrlShape.controlPoints[2]',f=1)
    pm.connectAttr('Tongue1CtrlBaseCurveInfo.controlPoints[3]','Tongue2CtrlShape.controlPoints[3]',f=1)
    pm.connectAttr('Tongue1CtrlBaseCurveInfo.controlPoints[4]','Tongue2CtrlShape.controlPoints[4]',f=1)
    pm.connectAttr('Tongue1CtrlBaseCurveInfo.controlPoints[0]','Tongue3CtrlShape.controlPoints[0]',f=1)
    pm.connectAttr('Tongue1CtrlBaseCurveInfo.controlPoints[1]','Tongue3CtrlShape.controlPoints[1]',f=1)
    pm.connectAttr('Tongue1CtrlBaseCurveInfo.controlPoints[2]','Tongue3CtrlShape.controlPoints[2]',f=1)
    pm.connectAttr('Tongue1CtrlBaseCurveInfo.controlPoints[3]','Tongue3CtrlShape.controlPoints[3]',f=1)
    pm.connectAttr('Tongue1CtrlBaseCurveInfo.controlPoints[4]','Tongue3CtrlShape.controlPoints[4]',f=1)
    pm.connectAttr('Tongue1CtrlBaseCurveInfo.controlPoints[0]','Tongue4CtrlShape.controlPoints[0]',f=1)
    pm.connectAttr('Tongue1CtrlBaseCurveInfo.controlPoints[1]','Tongue4CtrlShape.controlPoints[1]',f=1)
    pm.connectAttr('Tongue1CtrlBaseCurveInfo.controlPoints[2]','Tongue4CtrlShape.controlPoints[2]',f=1)
    pm.connectAttr('Tongue1CtrlBaseCurveInfo.controlPoints[3]','Tongue4CtrlShape.controlPoints[3]',f=1)
    pm.connectAttr('Tongue1CtrlBaseCurveInfo.controlPoints[4]','Tongue4CtrlShape.controlPoints[4]',f=1)
    pm.parent('Tongue1Ctrl','TongueFK1Ctrl')
    pm.parent('Tongue2Ctrl','TongueFK2Ctrl')
    pm.parent('Tongue3Ctrl','TongueFK3Ctrl')
    pm.parent('Tongue4Ctrl','TongueFK4Ctrl')
    pm.delete('Tongue1CtrlGrp')
    Utils.KGM_Aline("Tongue1Jnt", "TongueCtrlGrp", "p")
    Utils.KGM_Aline("Tongue2Jnt", "TongueFK1CtrlGrp", "a")
    Utils.KGM_Aline("Tongue3Jnt", "TongueFK2CtrlGrp", "a")
    Utils.KGM_Aline("Tongue4Jnt", "TongueFK3CtrlGrp", "a")
    Utils.KGM_Aline("Tongue5Jnt", "TongueFK4CtrlGrp", "a")
    Utils.KGM_Aline("Tongue6Jnt", "TongueFK5CtrlGrp", "a")
    Utils.KGM_Aline("Tongue6Jnt", "TongueIKCtrlGrp", "p")
    pm.parent('TongueFK2CtrlGrp','TongueFK1Ctrl')
    pm.parent('TongueFK3CtrlGrp','TongueFK2Ctrl')
    pm.parent('TongueFK4CtrlGrp','TongueFK3Ctrl')
    pm.parent('TongueFK5CtrlGrp','TongueFK4Ctrl')
    pm.group(em=1,n="TongueRigSysGrp")
    Utils.KGM_Aline("Tongue1Jnt", "TongueRigSysGrp", "p")
    pm.parent('TongueIKCtrlGrp','TongueCtrl')
    pm.parent('TongueFK1CtrlGrp','TongueCtrl')
    pm.duplicate('JntGuide_TongueGDCurve',rr=1,n="TongueIKChkCurve")
    pm.parent('TongueIKChkCurve',w=1)
    pm.delete('TongueIKChkCurveShapeOriginal')
    pm.rebuildCurve("TongueIKChkCurve",
        rt=0,ch=1,end=1,d=3,kr=0,s=4,kcp=0,tol=0.01,kt=0,rpo=1,kep=1)
    pm.delete('TongueIKChkCurve',ch=1)
    pm.duplicate('TongueIKChkCurve',rr=1,n="TongueIKCurve")
    pm.addAttr('TongueIKCtrl',ln="Twist",at='double')
    pm.setAttr('TongueIKCtrl.Twist',e=1,keyable=True)
    pm.addAttr('TongueIKCtrl',ln="Stretch",max=10,at='double',min=0)
    pm.setAttr('TongueIKCtrl.Stretch',e=1,keyable=True)
    pm.addAttr('TongueIKCtrl',ln="Squash",max=10,dv=0,at='double',min=0)
    pm.setAttr('TongueIKCtrl.Squash',e=1,keyable=True)
    pm.addAttr('TongueIKCtrl',ln="Follow",en="Tongue:Fly:World:",at="enum")
    pm.setAttr('TongueIKCtrl.Follow',e=1,keyable=True)
    #////////////////////
    #TongueFK1CtrlPoint
    #////////////////////
    pm.group(em=1,n="TongueFK1CtrlPoint")
    pm.group(em=1,n="TongueFK2CtrlPoint")
    pm.group(em=1,n="TongueFK3CtrlPoint")
    pm.group(em=1,n="TongueFK4CtrlPoint")
    pm.group(em=1,n="TongueFK5CtrlPoint")
    Utils.KGM_Aline("TongueFK1Ctrl", "TongueFK1CtrlPoint", "a")
    Utils.KGM_Aline("TongueFK2Ctrl", "TongueFK2CtrlPoint", "a")
    Utils.KGM_Aline("TongueFK3Ctrl", "TongueFK3CtrlPoint", "a")
    Utils.KGM_Aline("TongueFK4Ctrl", "TongueFK4CtrlPoint", "a")
    Utils.KGM_Aline("TongueFK5Ctrl", "TongueFK5CtrlPoint", "a")
    pm.parent('TongueFK5CtrlPoint','TongueFK4CtrlPoint')
    pm.parent('TongueFK4CtrlPoint','TongueFK3CtrlPoint')
    pm.parent('TongueFK3CtrlPoint','TongueFK2CtrlPoint')
    pm.parent('TongueFK2CtrlPoint','TongueFK1CtrlPoint')
    pm.parentConstraint('TongueIKRig2Jnt','TongueFK1CtrlPoint',weight=1,n="TongueFK1CtrlPointParentCon")
    pm.parentConstraint('TongueIKRig3Jnt','TongueFK2CtrlPoint',weight=1,n="TongueFK2CtrlPointParentCon")
    pm.parentConstraint('TongueIKRig4Jnt','TongueFK3CtrlPoint',weight=1,n="TongueFK3CtrlPointParentCon")
    pm.parentConstraint('TongueIKRig5Jnt','TongueFK4CtrlPoint',weight=1,n="TongueFK4CtrlPointParentCon")
    pm.parentConstraint('TongueIKRig6Jnt','TongueFK5CtrlPoint',weight=1,n="TongueFK5CtrlPointParentCon")
    #//////////////////////////
    #outline
    #//////////////////////////
    pm.parent('TongueRigSysGrp','TongueCtrl')
    pm.reorder('TongueRigSysGrp',relative=-2)
    pm.parent('TongueIKCtrlEndJnt','TongueIKCtrl')
    pm.parent('TongueIKCtrlJnt','TongueRigSysGrp')
    pm.parent('TongueIKRig1Jnt','TongueRigSysGrp')
    pm.parent('TongueFK1CtrlPoint','TongueRigSysGrp')
    pm.rename("TongueCtrlGrp","TongueRigGrp")
    pm.group(em=1,n="TongueSysGrp")
    pm.xform(os=1,piv=(0, 0, 0))
    pm.parent('TongueCtrlBaseGrp','TongueSysGrp')
    pm.parent('TongueFK1CtrlBaseGrp','TongueSysGrp')
    pm.parent('Tongue1CtrlBaseGrp','TongueSysGrp')
    pm.parent('TongueIKCtrlBaseGrp','TongueSysGrp')
    #/////////////////////////
    #Tongue IK 
    #/////////////////////////
    pm.ikHandle(c="TongueIKCurve",ccv=False,ee="TongueIKRig6Jnt",roc=False,pcv=False,sol='ikSplineSolver',sj="TongueIKRig1Jnt",ns=2)
    pm.rename("ikHandle1","TongueIKHandle")
    pm.rename("effector1","TongueIKEffector")
    #/////////////////////////
    #Tongue IK curve set 
    #/////////////////////////
    pm.skinCluster('TongueIKCtrlJnt','TongueIKCtrlEndJnt','TongueIKCurve',dr=4.0,tsb=1,mi=5,n="TongueSkinCluster")
    pm.rename("tweak1","TongueTweak")
    pm.rename("bindPose1","TongueCurveBindPose")
    pm.setAttr("TongueIKHandle.dTwistControlEnable",1)
    pm.setAttr('TongueIKHandle.dWorldUpType',4)
    pm.setAttr('TongueIKHandle.dWorldUpAxis',4)
    pm.setAttr("TongueIKHandle.dWorldUpVectorX",1)
    pm.setAttr("TongueIKHandle.dWorldUpVectorY",0)
    pm.setAttr("TongueIKHandle.dWorldUpVectorZ",0)
    pm.setAttr("TongueIKHandle.dWorldUpVectorEndX",1)
    pm.setAttr("TongueIKHandle.dWorldUpVectorEndY",0)
    pm.setAttr("TongueIKHandle.dWorldUpVectorEndZ",0)
    pm.connectAttr('TongueIKCtrlJnt.worldMatrix[0]','TongueIKHandle.dWorldUpMatrix',f=1)
    pm.connectAttr('TongueIKCtrlEndJnt.worldMatrix[0]','TongueIKHandle.dWorldUpMatrixEnd',f=1)
    pm.connectAttr('TongueIKCtrl.Twist','TongueIKHandle.twist',f=1)
    #set
    #TongueCtrl
    pm.parentConstraint('TongueCtrl','TongueJntScaleGrp',mo=1,weight=1,n="TongueJntScaleGrp")
    pm.connectAttr('TongueCtrl.scale','TongueJntScaleGrp.scale',f=1)
    #follow
    pm.group(em=1,n="TongueIKCtrlWorldPoint")
    pm.group(em=1,n="TongueIKCtrlFlyPoint")
    pm.group(em=1,n="TongueIKCtrlTonguePoint")
    Utils.KGM_Aline("Tongue6Jnt", "TongueIKCtrlWorldPoint", "p")
    Utils.KGM_Aline("Tongue6Jnt", "TongueIKCtrlFlyPoint", "p")
    Utils.KGM_Aline("Tongue6Jnt", "TongueIKCtrlTonguePoint", "p")
    pm.parent('TongueIKCtrlWorldPoint','WorldCtrl')
    pm.parent('TongueIKCtrlFlyPoint','FlyCtrl')
    pm.parent('TongueIKCtrlTonguePoint','TongueCtrl')
    pm.parentConstraint('TongueIKCtrlTonguePoint','TongueIKCtrlFlyPoint','TongueIKCtrlWorldPoint','TongueIKCtrlGrp',mo=1,weight=1,n="TongueIKCtrlGrpParentCon")
    pm.setAttr("TongueIKCtrl.Follow",1)
    pm.setAttr("TongueIKCtrlGrpParentCon.TongueIKCtrlTonguePointW0",0)
    pm.setAttr("TongueIKCtrlGrpParentCon.TongueIKCtrlFlyPointW1",1)
    pm.setAttr("TongueIKCtrlGrpParentCon.TongueIKCtrlWorldPointW2",0)
    pm.setDrivenKeyframe('TongueIKCtrlGrpParentCon.TongueIKCtrlTonguePointW0',currentDriver='TongueIKCtrl.Follow')
    pm.setDrivenKeyframe('TongueIKCtrlGrpParentCon.TongueIKCtrlFlyPointW1',currentDriver='TongueIKCtrl.Follow')
    pm.setDrivenKeyframe('TongueIKCtrlGrpParentCon.TongueIKCtrlWorldPointW2',currentDriver='TongueIKCtrl.Follow')
    pm.setAttr("TongueIKCtrl.Follow",2)
    pm.setAttr("TongueIKCtrlGrpParentCon.TongueIKCtrlTonguePointW0",0)
    pm.setAttr("TongueIKCtrlGrpParentCon.TongueIKCtrlFlyPointW1",0)
    pm.setAttr("TongueIKCtrlGrpParentCon.TongueIKCtrlWorldPointW2",1)
    pm.setDrivenKeyframe('TongueIKCtrlGrpParentCon.TongueIKCtrlTonguePointW0',currentDriver='TongueIKCtrl.Follow')
    pm.setDrivenKeyframe('TongueIKCtrlGrpParentCon.TongueIKCtrlFlyPointW1',currentDriver='TongueIKCtrl.Follow')
    pm.setDrivenKeyframe('TongueIKCtrlGrpParentCon.TongueIKCtrlWorldPointW2',currentDriver='TongueIKCtrl.Follow')
    pm.setAttr("TongueIKCtrl.Follow",0)
    pm.setAttr("TongueIKCtrlGrpParentCon.TongueIKCtrlTonguePointW0",1)
    pm.setAttr("TongueIKCtrlGrpParentCon.TongueIKCtrlFlyPointW1",0)
    pm.setAttr("TongueIKCtrlGrpParentCon.TongueIKCtrlWorldPointW2",0)
    pm.setDrivenKeyframe('TongueIKCtrlGrpParentCon.TongueIKCtrlTonguePointW0',currentDriver='TongueIKCtrl.Follow')
    pm.setDrivenKeyframe('TongueIKCtrlGrpParentCon.TongueIKCtrlFlyPointW1',currentDriver='TongueIKCtrl.Follow')
    pm.setDrivenKeyframe('TongueIKCtrlGrpParentCon.TongueIKCtrlWorldPointW2',currentDriver='TongueIKCtrl.Follow')
    #/////////////////////////
    #
    #/////////////////////////
    pm.connectAttr('TongueFK1CtrlPoint.translate','TongueFK1CtrlGrp.translate',f=1)
    pm.connectAttr('TongueFK1CtrlPoint.rotate','TongueFK1CtrlGrp.rotate',f=1)
    pm.connectAttr('TongueFK2CtrlPoint.translate','TongueFK2CtrlGrp.translate',f=1)
    pm.connectAttr('TongueFK2CtrlPoint.rotate','TongueFK2CtrlGrp.rotate',f=1)
    pm.connectAttr('TongueFK3CtrlPoint.translate','TongueFK3CtrlGrp.translate',f=1)
    pm.connectAttr('TongueFK3CtrlPoint.rotate','TongueFK3CtrlGrp.rotate',f=1)
    pm.connectAttr('TongueFK4CtrlPoint.translate','TongueFK4CtrlGrp.translate',f=1)
    pm.connectAttr('TongueFK4CtrlPoint.rotate','TongueFK4CtrlGrp.rotate',f=1)
    pm.connectAttr('TongueFK5CtrlPoint.translate','TongueFK5CtrlGrp.translate',f=1)
    pm.connectAttr('TongueFK5CtrlPoint.rotate','TongueFK5CtrlGrp.rotate',f=1)
    #/////////////////////////
    #scale set
    #/////////////////////////
    pm.parentConstraint('TongueIKRig1Jnt','Tongue1Jnt',mo=1,weight=1,n="Tongue1JntParentCon")
    pm.parentConstraint('Tongue1Ctrl','Tongue2Jnt',mo=1,weight=1,n="Tongue2JntParentCon")
    pm.parentConstraint('Tongue2Ctrl','Tongue3Jnt',mo=1,weight=1,n="Tongue3JntParentCon")
    pm.parentConstraint('Tongue3Ctrl','Tongue4Jnt',mo=1,weight=1,n="Tongue4JntParentCon")
    pm.parentConstraint('Tongue4Ctrl','Tongue5Jnt',mo=1,weight=1,n="Tongue5JntParentCon")
    pm.parentConstraint('TongueFK5Ctrl','Tongue6Jnt',mo=1,weight=1,n="Tongue6JntParentCon")
    #/////////////////////////
    #TongueIKCurve length
    #/////////////////////////
    pm.createNode('pointOnCurveInfo',n="TongueIKCurvePointInfo1")
    pm.createNode('pointOnCurveInfo',n="TongueIKCurvePointInfo2")
    pm.createNode('pointOnCurveInfo',n="TongueIKCurvePointInfo3")
    pm.createNode('pointOnCurveInfo',n="TongueIKCurvePointInfo4")
    pm.createNode('pointOnCurveInfo',n="TongueIKCurvePointInfo5")
    pm.createNode('pointOnCurveInfo',n="TongueIKCurvePointInfo6")
    pm.setAttr("TongueIKCurvePointInfo1.turnOnPercentage",1)
    pm.setAttr("TongueIKCurvePointInfo2.turnOnPercentage",1)
    pm.setAttr("TongueIKCurvePointInfo3.turnOnPercentage",1)
    pm.setAttr("TongueIKCurvePointInfo4.turnOnPercentage",1)
    pm.setAttr("TongueIKCurvePointInfo5.turnOnPercentage",1)
    pm.setAttr("TongueIKCurvePointInfo6.turnOnPercentage",1)
    pm.connectAttr('TongueIKCurveShape.worldSpace[0]','TongueIKCurvePointInfo1.inputCurve',f=1)
    pm.connectAttr('TongueIKCurveShape.worldSpace[0]','TongueIKCurvePointInfo2.inputCurve',f=1)
    pm.connectAttr('TongueIKCurveShape.worldSpace[0]','TongueIKCurvePointInfo3.inputCurve',f=1)
    pm.connectAttr('TongueIKCurveShape.worldSpace[0]','TongueIKCurvePointInfo4.inputCurve',f=1)
    pm.connectAttr('TongueIKCurveShape.worldSpace[0]','TongueIKCurvePointInfo5.inputCurve',f=1)
    pm.connectAttr('TongueIKCurveShape.worldSpace[0]','TongueIKCurvePointInfo6.inputCurve',f=1)
    pm.setAttr("TongueIKCurvePointInfo1.parameter",
        pm.getAttr('JntGuide_TongueMotionPath1.uValue'))
    pm.setAttr("TongueIKCurvePointInfo2.parameter",
        pm.getAttr('JntGuide_TongueMotionPath2.uValue'))
    pm.setAttr("TongueIKCurvePointInfo3.parameter",
        pm.getAttr('JntGuide_TongueMotionPath3.uValue'))
    pm.setAttr("TongueIKCurvePointInfo4.parameter",
        pm.getAttr('JntGuide_TongueMotionPath4.uValue'))
    pm.setAttr("TongueIKCurvePointInfo5.parameter",
        pm.getAttr('JntGuide_TongueMotionPath5.uValue'))
    pm.setAttr("TongueIKCurvePointInfo6.parameter",
        pm.getAttr('JntGuide_TongueMotionPath6.uValue'))
    pm.createNode('distanceBetween',n="TongueDistance1")
    pm.createNode('distanceBetween',n="TongueDistance2")
    pm.createNode('distanceBetween',n="TongueDistance3")
    pm.createNode('distanceBetween',n="TongueDistance4")
    pm.createNode('distanceBetween',n="TongueDistance5")
    pm.connectAttr('TongueIKCurvePointInfo1.position','TongueDistance1.point1',f=1)
    pm.connectAttr('TongueIKCurvePointInfo2.position','TongueDistance1.point2',f=1)
    pm.connectAttr('TongueIKCurvePointInfo2.position','TongueDistance2.point1',f=1)
    pm.connectAttr('TongueIKCurvePointInfo3.position','TongueDistance2.point2',f=1)
    pm.connectAttr('TongueIKCurvePointInfo3.position','TongueDistance3.point1',f=1)
    pm.connectAttr('TongueIKCurvePointInfo4.position','TongueDistance3.point2',f=1)
    pm.connectAttr('TongueIKCurvePointInfo4.position','TongueDistance4.point1',f=1)
    pm.connectAttr('TongueIKCurvePointInfo5.position','TongueDistance4.point2',f=1)
    pm.connectAttr('TongueIKCurvePointInfo5.position','TongueDistance5.point1',f=1)
    pm.connectAttr('TongueIKCurvePointInfo6.position','TongueDistance5.point2',f=1)
    #/////////////////////////
    #TongueIKChkCurve length
    #/////////////////////////
    pm.createNode('pointOnCurveInfo',n="TongueIKChkCurvePointInfo1")
    pm.createNode('pointOnCurveInfo',n="TongueIKChkCurvePointInfo2")
    pm.createNode('pointOnCurveInfo',n="TongueIKChkCurvePointInfo3")
    pm.createNode('pointOnCurveInfo',n="TongueIKChkCurvePointInfo4")
    pm.createNode('pointOnCurveInfo',n="TongueIKChkCurvePointInfo5")
    pm.createNode('pointOnCurveInfo',n="TongueIKChkCurvePointInfo6")
    pm.setAttr("TongueIKChkCurvePointInfo1.turnOnPercentage",1)
    pm.setAttr("TongueIKChkCurvePointInfo2.turnOnPercentage",1)
    pm.setAttr("TongueIKChkCurvePointInfo3.turnOnPercentage",1)
    pm.setAttr("TongueIKChkCurvePointInfo4.turnOnPercentage",1)
    pm.setAttr("TongueIKChkCurvePointInfo5.turnOnPercentage",1)
    pm.setAttr("TongueIKChkCurvePointInfo6.turnOnPercentage",1)
    pm.connectAttr('TongueIKChkCurveShape.worldSpace[0]','TongueIKChkCurvePointInfo1.inputCurve',f=1)
    pm.connectAttr('TongueIKChkCurveShape.worldSpace[0]','TongueIKChkCurvePointInfo2.inputCurve',f=1)
    pm.connectAttr('TongueIKChkCurveShape.worldSpace[0]','TongueIKChkCurvePointInfo3.inputCurve',f=1)
    pm.connectAttr('TongueIKChkCurveShape.worldSpace[0]','TongueIKChkCurvePointInfo4.inputCurve',f=1)
    pm.connectAttr('TongueIKChkCurveShape.worldSpace[0]','TongueIKChkCurvePointInfo5.inputCurve',f=1)
    pm.connectAttr('TongueIKChkCurveShape.worldSpace[0]','TongueIKChkCurvePointInfo6.inputCurve',f=1)
    pm.setAttr("TongueIKChkCurvePointInfo1.parameter",
        pm.getAttr('JntGuide_TongueMotionPath1.uValue'))
    pm.setAttr("TongueIKChkCurvePointInfo2.parameter",
        pm.getAttr('JntGuide_TongueMotionPath2.uValue'))
    pm.setAttr("TongueIKChkCurvePointInfo3.parameter",
        pm.getAttr('JntGuide_TongueMotionPath3.uValue'))
    pm.setAttr("TongueIKChkCurvePointInfo4.parameter",
        pm.getAttr('JntGuide_TongueMotionPath4.uValue'))
    pm.setAttr("TongueIKChkCurvePointInfo5.parameter",
        pm.getAttr('JntGuide_TongueMotionPath5.uValue'))
    pm.setAttr("TongueIKChkCurvePointInfo6.parameter",
        pm.getAttr('JntGuide_TongueMotionPath6.uValue'))
    pm.createNode('distanceBetween',n="TongueChkDistance1")
    pm.createNode('distanceBetween',n="TongueChkDistance2")
    pm.createNode('distanceBetween',n="TongueChkDistance3")
    pm.createNode('distanceBetween',n="TongueChkDistance4")
    pm.createNode('distanceBetween',n="TongueChkDistance5")
    pm.connectAttr('TongueIKChkCurvePointInfo1.position','TongueChkDistance1.point1',f=1)
    pm.connectAttr('TongueIKChkCurvePointInfo2.position','TongueChkDistance1.point2',f=1)
    pm.connectAttr('TongueIKChkCurvePointInfo2.position','TongueChkDistance2.point1',f=1)
    pm.connectAttr('TongueIKChkCurvePointInfo3.position','TongueChkDistance2.point2',f=1)
    pm.connectAttr('TongueIKChkCurvePointInfo3.position','TongueChkDistance3.point1',f=1)
    pm.connectAttr('TongueIKChkCurvePointInfo4.position','TongueChkDistance3.point2',f=1)
    pm.connectAttr('TongueIKChkCurvePointInfo4.position','TongueChkDistance4.point1',f=1)
    pm.connectAttr('TongueIKChkCurvePointInfo5.position','TongueChkDistance4.point2',f=1)
    pm.connectAttr('TongueIKChkCurvePointInfo5.position','TongueChkDistance5.point1',f=1)
    pm.connectAttr('TongueIKChkCurvePointInfo6.position','TongueChkDistance5.point2',f=1)
    #/////////////////////////
    #Stretch blend Attr
    #/////////////////////////
    pm.createNode('blendTwoAttr',n="TongueStretchBlend1")
    pm.createNode('blendTwoAttr',n="TongueStretchBlend2")
    pm.createNode('blendTwoAttr',n="TongueStretchBlend3")
    pm.createNode('blendTwoAttr',n="TongueStretchBlend4")
    pm.createNode('blendTwoAttr',n="TongueStretchBlend5")
    pm.connectAttr('TongueChkDistance1.distance','TongueStretchBlend1.input[0]',f=1)
    pm.connectAttr('TongueDistance1.distance','TongueStretchBlend1.input[1]',f=1)
    pm.connectAttr('TongueChkDistance2.distance','TongueStretchBlend2.input[0]',f=1)
    pm.connectAttr('TongueDistance2.distance','TongueStretchBlend2.input[1]',f=1)
    pm.connectAttr('TongueChkDistance3.distance','TongueStretchBlend3.input[0]',f=1)
    pm.connectAttr('TongueDistance3.distance','TongueStretchBlend3.input[1]',f=1)
    pm.connectAttr('TongueChkDistance4.distance','TongueStretchBlend4.input[0]',f=1)
    pm.connectAttr('TongueDistance4.distance','TongueStretchBlend4.input[1]',f=1)
    pm.connectAttr('TongueChkDistance5.distance','TongueStretchBlend5.input[0]',f=1)
    pm.connectAttr('TongueDistance5.distance','TongueStretchBlend5.input[1]',f=1)
    pm.createNode('multDoubleLinear',n="TongueStretchMulti")
    pm.setAttr("TongueStretchMulti.input2",0.1)
    pm.connectAttr('TongueIKCtrl.Stretch','TongueStretchMulti.input1',f=1)
    pm.connectAttr('TongueStretchMulti.output','TongueStretchBlend1.attributesBlender',f=1)
    pm.connectAttr('TongueStretchMulti.output','TongueStretchBlend2.attributesBlender',f=1)
    pm.connectAttr('TongueStretchMulti.output','TongueStretchBlend3.attributesBlender',f=1)
    pm.connectAttr('TongueStretchMulti.output','TongueStretchBlend4.attributesBlender',f=1)
    pm.connectAttr('TongueStretchMulti.output','TongueStretchBlend5.attributesBlender',f=1)
    #//////////////////////
    #TongueDistanceDivide 
    #//////////////////////
    pm.createNode('multiplyDivide',n="TongueDistanceDivide1")
    pm.createNode('multiplyDivide',n="TongueDistanceDivide2")
    pm.createNode('multiplyDivide',n="TongueDistanceDivide3")
    pm.createNode('multiplyDivide',n="TongueDistanceDivide4")
    pm.createNode('multiplyDivide',n="TongueDistanceDivide5")
    pm.setAttr('TongueDistanceDivide1.operation',2)
    pm.setAttr('TongueDistanceDivide2.operation',2)
    pm.setAttr('TongueDistanceDivide3.operation',2)
    pm.setAttr('TongueDistanceDivide4.operation',2)
    pm.setAttr('TongueDistanceDivide5.operation',2)
    pm.connectAttr('TongueStretchBlend1.output','TongueDistanceDivide1.input1X',f=1)
    pm.connectAttr('TongueStretchBlend1.output','TongueDistanceDivide1.input2Y',f=1)
    pm.connectAttr('TongueStretchBlend2.output','TongueDistanceDivide2.input1X',f=1)
    pm.connectAttr('TongueStretchBlend2.output','TongueDistanceDivide2.input2Y',f=1)
    pm.connectAttr('TongueStretchBlend3.output','TongueDistanceDivide3.input1X',f=1)
    pm.connectAttr('TongueStretchBlend3.output','TongueDistanceDivide3.input2Y',f=1)
    pm.connectAttr('TongueStretchBlend4.output','TongueDistanceDivide4.input1X',f=1)
    pm.connectAttr('TongueStretchBlend4.output','TongueDistanceDivide4.input2Y',f=1)
    pm.connectAttr('TongueStretchBlend5.output','TongueDistanceDivide5.input1X',f=1)
    pm.connectAttr('TongueStretchBlend5.output','TongueDistanceDivide5.input2Y',f=1)
    pm.connectAttr('TongueChkDistance1.distance','TongueDistanceDivide1.input2X',f=1)
    pm.connectAttr('TongueChkDistance1.distance','TongueDistanceDivide1.input1Y',f=1)
    pm.connectAttr('TongueChkDistance2.distance','TongueDistanceDivide2.input2X',f=1)
    pm.connectAttr('TongueChkDistance2.distance','TongueDistanceDivide2.input1Y',f=1)
    pm.connectAttr('TongueChkDistance3.distance','TongueDistanceDivide3.input2X',f=1)
    pm.connectAttr('TongueChkDistance3.distance','TongueDistanceDivide3.input1Y',f=1)
    pm.connectAttr('TongueChkDistance4.distance','TongueDistanceDivide4.input2X',f=1)
    pm.connectAttr('TongueChkDistance4.distance','TongueDistanceDivide4.input1Y',f=1)
    pm.connectAttr('TongueChkDistance5.distance','TongueDistanceDivide5.input2X',f=1)
    pm.connectAttr('TongueChkDistance5.distance','TongueDistanceDivide5.input1Y',f=1)
    #/////////////////////////
    #streath X
    #/////////////////////////
    pm.createNode('multDoubleLinear',n="TongueTransMulti1")
    pm.createNode('multDoubleLinear',n="TongueTransMulti2")
    pm.createNode('multDoubleLinear',n="TongueTransMulti3")
    pm.createNode('multDoubleLinear',n="TongueTransMulti4")
    pm.createNode('multDoubleLinear',n="TongueTransMulti5")
    pm.connectAttr('TongueDistanceDivide1.outputX','TongueTransMulti1.input1',f=1)
    pm.connectAttr('TongueDistanceDivide2.outputX','TongueTransMulti2.input1',f=1)
    pm.connectAttr('TongueDistanceDivide3.outputX','TongueTransMulti3.input1',f=1)
    pm.connectAttr('TongueDistanceDivide4.outputX','TongueTransMulti4.input1',f=1)
    pm.connectAttr('TongueDistanceDivide5.outputX','TongueTransMulti5.input1',f=1)
    pm.setAttr("TongueTransMulti1.input2",
        pm.getAttr('TongueIKRig2Jnt.translateX'))
    pm.setAttr("TongueTransMulti2.input2",
        pm.getAttr('TongueIKRig3Jnt.translateX'))
    pm.setAttr("TongueTransMulti3.input2",
        pm.getAttr('TongueIKRig4Jnt.translateX'))
    pm.setAttr("TongueTransMulti4.input2",
        pm.getAttr('TongueIKRig5Jnt.translateX'))
    pm.setAttr("TongueTransMulti5.input2",
        pm.getAttr('TongueIKRig6Jnt.translateX'))
    pm.connectAttr('TongueTransMulti1.output','TongueIKRig2Jnt.translateX',f=1)
    pm.connectAttr('TongueTransMulti2.output','TongueIKRig3Jnt.translateX',f=1)
    pm.connectAttr('TongueTransMulti3.output','TongueIKRig4Jnt.translateX',f=1)
    pm.connectAttr('TongueTransMulti4.output','TongueIKRig5Jnt.translateX',f=1)
    pm.connectAttr('TongueTransMulti5.output','TongueIKRig6Jnt.translateX',f=1)
    #/////////////////////////
    #Tongue Squash Blend
    #/////////////////////////
    pm.createNode('blendTwoAttr',n="TongueSquashBlend1")
    pm.createNode('blendTwoAttr',n="TongueSquashBlend2")
    pm.createNode('blendTwoAttr',n="TongueSquashBlend3")
    pm.createNode('blendTwoAttr',n="TongueSquashBlend4")
    pm.createNode('blendTwoAttr',n="TongueSquashBlend5")
    pm.connectAttr('TongueDistanceDivide1.outputY','TongueSquashBlend1.input[1]',f=1)
    pm.connectAttr('TongueDistanceDivide2.outputY','TongueSquashBlend2.input[1]',f=1)
    pm.connectAttr('TongueDistanceDivide3.outputY','TongueSquashBlend3.input[1]',f=1)
    pm.connectAttr('TongueDistanceDivide4.outputY','TongueSquashBlend4.input[1]',f=1)
    pm.connectAttr('TongueDistanceDivide5.outputY','TongueSquashBlend5.input[1]',f=1)
    pm.setAttr("TongueSquashBlend1.input[0]",1)
    pm.setAttr("TongueSquashBlend2.input[0]",1)
    pm.setAttr("TongueSquashBlend3.input[0]",1)
    pm.setAttr("TongueSquashBlend4.input[0]",1)
    pm.setAttr("TongueSquashBlend5.input[0]",1)
    pm.createNode('multDoubleLinear',n="TongueSquashMulti")
    pm.setAttr("TongueSquashMulti.input2",0.1)
    pm.connectAttr('TongueIKCtrl.Squash','TongueSquashMulti.input1',f=1)
    pm.connectAttr('TongueSquashMulti.output','TongueSquashBlend1.attributesBlender',f=1)
    pm.connectAttr('TongueSquashMulti.output','TongueSquashBlend2.attributesBlender',f=1)
    pm.connectAttr('TongueSquashMulti.output','TongueSquashBlend3.attributesBlender',f=1)
    pm.connectAttr('TongueSquashMulti.output','TongueSquashBlend4.attributesBlender',f=1)
    pm.connectAttr('TongueSquashMulti.output','TongueSquashBlend5.attributesBlender',f=1)
    #///////////////////////////
    #ToingueSquashBalanceBlend 
    #///////////////////////////
    pm.createNode('blendTwoAttr',n="TongueSquashBalanceBlend2")
    pm.createNode('blendTwoAttr',n="TongueSquashBalanceBlend3")
    pm.createNode('blendTwoAttr',n="TongueSquashBalanceBlend4")
    pm.createNode('blendTwoAttr',n="TongueSquashBalanceBlend5")
    pm.createNode('blendTwoAttr',n="TongueSquashBalanceBlend6")
    pm.setAttr("TongueSquashBalanceBlend2.attributesBlender",1)
    pm.setAttr("TongueSquashBalanceBlend3.attributesBlender",1)
    pm.setAttr("TongueSquashBalanceBlend4.attributesBlender",0.912)
    pm.setAttr("TongueSquashBalanceBlend5.attributesBlender",0.622)
    pm.setAttr("TongueSquashBalanceBlend6.attributesBlender",0.500)
    pm.setAttr("TongueSquashBalanceBlend2.input[0]",1)
    pm.setAttr("TongueSquashBalanceBlend3.input[0]",1)
    pm.setAttr("TongueSquashBalanceBlend4.input[0]",1)
    pm.setAttr("TongueSquashBalanceBlend5.input[0]",1)
    pm.setAttr("TongueSquashBalanceBlend6.input[0]",1)
    pm.connectAttr('TongueSquashBlend1.output','TongueSquashBalanceBlend2.input[1]',f=1)
    pm.connectAttr('TongueSquashBlend2.output','TongueSquashBalanceBlend3.input[1]',f=1)
    pm.connectAttr('TongueSquashBlend3.output','TongueSquashBalanceBlend4.input[1]',f=1)
    pm.connectAttr('TongueSquashBlend4.output','TongueSquashBalanceBlend5.input[1]',f=1)
    pm.connectAttr('TongueSquashBlend5.output','TongueSquashBalanceBlend6.input[1]',f=1)
    #///////////////////////////
    #TongueSquashScaleMulti 
    #///////////////////////////
    pm.createNode('multiplyDivide',n="TongueSquashScaleMulti1")
    pm.createNode('multiplyDivide',n="TongueSquashScaleMulti2")
    pm.createNode('multiplyDivide',n="TongueSquashScaleMulti3")
    pm.createNode('multiplyDivide',n="TongueSquashScaleMulti4")
    pm.createNode('multiplyDivide',n="TongueSquashScaleMulti5")
    pm.setAttr('TongueSquashScaleMulti1.operation',1)
    pm.setAttr('TongueSquashScaleMulti2.operation',1)
    pm.setAttr('TongueSquashScaleMulti3.operation',1)
    pm.setAttr('TongueSquashScaleMulti4.operation',1)
    pm.setAttr('TongueSquashScaleMulti5.operation',1)
    pm.setAttr("TongueSquashScaleMulti1.input1X",1)
    pm.setAttr("TongueSquashScaleMulti2.input1X",1)
    pm.setAttr("TongueSquashScaleMulti3.input1X",1)
    pm.setAttr("TongueSquashScaleMulti4.input1X",1)
    pm.setAttr("TongueSquashScaleMulti5.input1X",1)
    pm.connectAttr('TongueSquashBalanceBlend2.output','TongueSquashScaleMulti1.input1Y',f=1)
    pm.connectAttr('TongueSquashBalanceBlend2.output','TongueSquashScaleMulti1.input1Z',f=1)
    pm.connectAttr('TongueSquashBalanceBlend3.output','TongueSquashScaleMulti2.input1Y',f=1)
    pm.connectAttr('TongueSquashBalanceBlend3.output','TongueSquashScaleMulti2.input1Z',f=1)
    pm.connectAttr('TongueSquashBalanceBlend4.output','TongueSquashScaleMulti3.input1Y',f=1)
    pm.connectAttr('TongueSquashBalanceBlend4.output','TongueSquashScaleMulti3.input1Z',f=1)
    pm.connectAttr('TongueSquashBalanceBlend5.output','TongueSquashScaleMulti4.input1Y',f=1)
    pm.connectAttr('TongueSquashBalanceBlend5.output','TongueSquashScaleMulti4.input1Z',f=1)
    pm.connectAttr('TongueSquashBalanceBlend6.output','TongueSquashScaleMulti5.input1Y',f=1)
    pm.connectAttr('TongueSquashBalanceBlend6.output','TongueSquashScaleMulti5.input1Z',f=1)
    pm.connectAttr('Tongue1Ctrl.scale','TongueSquashScaleMulti1.input2',f=1)
    pm.connectAttr('Tongue2Ctrl.scale','TongueSquashScaleMulti2.input2',f=1)
    pm.connectAttr('Tongue3Ctrl.scale','TongueSquashScaleMulti3.input2',f=1)
    pm.connectAttr('Tongue4Ctrl.scale','TongueSquashScaleMulti4.input2',f=1)
    pm.connectAttr('TongueFK5Ctrl.scale','TongueSquashScaleMulti5.input2',f=1)
    #///////////////////////////
    #TongueBindJntScaleMulti 
    #///////////////////////////
    pm.createNode('multiplyDivide',n="TongueBindJntScaleMulti1")
    pm.createNode('multiplyDivide',n="TongueBindJntScaleMulti2")
    pm.createNode('multiplyDivide',n="TongueBindJntScaleMulti3")
    pm.createNode('multiplyDivide',n="TongueBindJntScaleMulti4")
    pm.createNode('multiplyDivide',n="TongueBindJntScaleMulti5")
    pm.setAttr('TongueBindJntScaleMulti1.operation',1)
    pm.setAttr('TongueBindJntScaleMulti2.operation',1)
    pm.setAttr('TongueBindJntScaleMulti3.operation',1)
    pm.setAttr('TongueBindJntScaleMulti4.operation',1)
    pm.setAttr('TongueBindJntScaleMulti5.operation',1)
    pm.connectAttr('TongueSquashScaleMulti1.output','TongueBindJntScaleMulti1.input2',f=1)
    pm.connectAttr('TongueSquashScaleMulti2.output','TongueBindJntScaleMulti2.input2',f=1)
    pm.connectAttr('TongueSquashScaleMulti3.output','TongueBindJntScaleMulti3.input2',f=1)
    pm.connectAttr('TongueSquashScaleMulti4.output','TongueBindJntScaleMulti4.input2',f=1)
    pm.connectAttr('TongueSquashScaleMulti5.output','TongueBindJntScaleMulti5.input2',f=1)
    #/////////////////////////
    #TongueFK ScaleMulti
    #/////////////////////////
    pm.connectAttr('TongueFK1Ctrl.scale','TongueBindJntScaleMulti1.input1',f=1)
    pm.createNode('multiplyDivide',n="TongueFK1ScaleMulti")
    pm.createNode('multiplyDivide',n="TongueFK2ScaleMulti")
    pm.createNode('multiplyDivide',n="TongueFK3ScaleMulti")
    pm.createNode('multiplyDivide',n="TongueFK4ScaleMulti")
    pm.setAttr('TongueFK1ScaleMulti.operation',1)
    pm.setAttr('TongueFK2ScaleMulti.operation',1)
    pm.setAttr('TongueFK3ScaleMulti.operation',1)
    pm.setAttr('TongueFK4ScaleMulti.operation',1)
    pm.setAttr("TongueFK1ScaleMulti.input2X",1)
    pm.setAttr("TongueFK1ScaleMulti.input2Y",1)
    pm.setAttr("TongueFK1ScaleMulti.input2Z",1)
    pm.connectAttr('TongueFK1Ctrl.scale','TongueFK1ScaleMulti.input1',f=1)
    pm.connectAttr('TongueFK2Ctrl.scale','TongueFK2ScaleMulti.input1',f=1)
    pm.connectAttr('TongueFK3Ctrl.scale','TongueFK3ScaleMulti.input1',f=1)
    pm.connectAttr('TongueFK4Ctrl.scale','TongueFK4ScaleMulti.input1',f=1)
    pm.connectAttr('TongueFK1ScaleMulti.output','TongueBindJntScaleMulti2.input1',f=1)
    pm.connectAttr('TongueFK2ScaleMulti.output','TongueBindJntScaleMulti3.input1',f=1)
    pm.connectAttr('TongueFK3ScaleMulti.output','TongueBindJntScaleMulti4.input1',f=1)
    pm.connectAttr('TongueFK4ScaleMulti.output','TongueBindJntScaleMulti5.input1',f=1)
    pm.connectAttr('TongueFK1ScaleMulti.output','TongueFK2ScaleMulti.input2',f=1)
    pm.connectAttr('TongueFK2ScaleMulti.output','TongueFK3ScaleMulti.input2',f=1)
    pm.connectAttr('TongueFK3ScaleMulti.output','TongueFK4ScaleMulti.input2',f=1)
    #//////////////////////
    # Tongue Jnt scale
    #//////////////////////
    pm.connectAttr('TongueBindJntScaleMulti1.output','Tongue2Jnt.scale',f=1)
    pm.connectAttr('TongueBindJntScaleMulti2.output','Tongue3Jnt.scale',f=1)
    pm.connectAttr('TongueBindJntScaleMulti3.output','Tongue4Jnt.scale',f=1)
    pm.connectAttr('TongueBindJntScaleMulti4.output','Tongue5Jnt.scale',f=1)
    pm.connectAttr('TongueBindJntScaleMulti5.output','Tongue6Jnt.scale',f=1)
    #///////////////////////
    #outline
    #///////////////////////
    pm.parent('TongueIKChkCurve','TongueRigSysGrp')
    pm.parent('TongueIKHandle','TongueRigSysGrp')
    pm.parent('TongueRigGrp','JawCtrl')
    pm.parent('TongueIKCurve','TongueSysGrp')
    pm.parent('TongueSysGrp','RigSysGrp')
    #//////////////////////
    #shape set
    #//////////////////////
    pm.addAttr('TongueSysGrp',ln="TongueCtrlsRadiusY",at='double')
    pm.setAttr('TongueSysGrp.TongueCtrlsRadiusY',e=1,channelBox=True)
    pm.addAttr('TongueSysGrp',ln="TongueCtrlsRadiusZ",at='double')
    pm.setAttr('TongueSysGrp.TongueCtrlsRadiusZ',e=1,channelBox=True)
    #connectAttr -f TongueSysGrp.TongueCtrlsRadiusY TongueCtrlBase.scaleZ;
    pm.connectAttr('TongueSysGrp.TongueCtrlsRadiusZ','TongueCtrlBase.scaleX',f=1)
    pm.connectAttr('TongueSysGrp.TongueCtrlsRadiusY','TongueFK1CtrlBase.scaleY',f=1)
    pm.connectAttr('TongueSysGrp.TongueCtrlsRadiusZ','TongueFK1CtrlBase.scaleZ',f=1)
    pm.connectAttr('TongueSysGrp.TongueCtrlsRadiusY','Tongue1CtrlBase.scaleY',f=1)
    pm.connectAttr('TongueSysGrp.TongueCtrlsRadiusZ','Tongue1CtrlBase.scaleZ',f=1)
    pm.connectAttr('TongueSysGrp.TongueCtrlsRadiusY','TongueIKCtrlBase.scaleY',f=1)
    pm.connectAttr('TongueSysGrp.TongueCtrlsRadiusZ','TongueIKCtrlBase.scaleZ',f=1)
    #default
    pm.setAttr("TongueSysGrp.TongueCtrlsRadiusY",0.5)
    pm.setAttr("TongueSysGrp.TongueCtrlsRadiusZ",0.5)
    pm.setAttr("TongueIKCtrlBase.rotateY",-90)
    
    


