import pymel.core as pm
import Core_GMKRig.Utils as Utils
reload(Utils)

def KGM_OutlinSet():
    pm.reorder('RightClavicleCtrlGrp',relative=-4)
    pm.reorder('RightArmRigGrp',relative=-4)
    pm.reorder('LeftClavicleCtrlGrp',relative=-2)
    pm.reorder('LeftArmRigGrp',relative=-2)
    pm.reorder('RightLegRigGrp',relative=-1)
    pm.reorder('RightLegIKCtrlFlyPoint',relative=-1)
    pm.reorder('LeftArmIKCtrlFlyPoint',relative=-1)
    pm.reorder('RightLegIKCtrlWorldPoint',relative=-1)
    pm.group(em=1,n="BsSysGrp")
    pm.group(em=1,n="BsFaceSysGrp")
    pm.group(em=1,n="BsBodySysGrp")
    pm.group(em=1,n="BsExtSysGrp")
    pm.group(em=1,n="BsFaceTargetGrp")
    pm.group(em=1,n="BsFaceRigGrp")
    pm.group(em=1,n="BsBodyTargetGrp")
    pm.group(em=1,n="BsBodyRigGrp")
    pm.group(em=1,n="BsExtTargetGrp")
    pm.group(em=1,n="BsExtRigGrp")
    pm.parent('BsFaceTargetGrp','BsFaceSysGrp')
    pm.parent('BsFaceRigGrp','BsFaceSysGrp')
    pm.parent('BsBodyTargetGrp','BsBodySysGrp')
    pm.parent('BsBodyRigGrp','BsBodySysGrp')
    pm.parent('BsExtTargetGrp','BsExtSysGrp')
    pm.parent('BsExtRigGrp','BsExtSysGrp')
    pm.parent('BsFaceSysGrp','BsSysGrp')
    pm.parent('BsBodySysGrp','BsSysGrp')
    pm.parent('BsExtSysGrp','BsSysGrp')
    pm.parent('BsSysGrp','RigSysGrp')
    #remove reference
    #pm.cmds.file(os.environ["GMKIM_RIGGING"] + "/JointGuide/Bipad/KGM_JntGD.ma",removeReference=1)
    pm.cmds.file(Utils.get_GMKRigPath() + "/Bipad/KGM_JntGD.ma",removeReference=1)