import pymel.core as pm
import Core_GMKRig.Utils as Utils
reload(Utils)

def KGM_RebuildJnt():
    #///////////////////////
    #Joint ReBuild
    #//////////////////////

    #Head 
    Utils.KGM_DuplicateJnt("HeadJnt", "HeadScaleFixJnt")
    pm.parent('HeadScaleFixJnt','Neck3Jnt')
    pm.group(em=1,n="HeadScaleConnectGrp")
    pm.group(em=1,n="HeadScaleSquashGrp")
    pm.parent('HeadScaleSquashGrp','HeadScaleConnectGrp')
    pm.parent('HeadScaleConnectGrp','HeadScaleFixJnt')
    pm.setAttr("HeadScaleConnectGrp.translateX",0)
    pm.setAttr("HeadScaleConnectGrp.translateY",0)
    pm.setAttr("HeadScaleConnectGrp.translateZ",0)
    pm.parent('HeadJnt','HeadScaleSquashGrp')
    #Lefteye
    pm.group(em=1,n="LeftEyeScaleConnectGrp")
    Utils.KGM_Aline("LeftEyeJnt", "LeftEyeScaleConnectGrp", "a")
    Utils.KGM_DuplicateJnt("LeftEyeJnt", "LeftEyeScaleJnt")
    pm.parent('LeftEyeScaleJnt','LeftEyeScaleConnectGrp')
    pm.parent('LeftEyeJnt','LeftEyeScaleJnt')
    pm.parent('LeftEyeScaleConnectGrp','HeadJnt')
    #Right eye
    pm.group(em=1,n="RightEyeScaleConnectGrp")
    Utils.KGM_Aline("RightEyeJnt", "RightEyeScaleConnectGrp", "a")
    Utils.KGM_DuplicateJnt("RightEyeJnt", "RightEyeScaleJnt")
    pm.parent('RightEyeScaleJnt','RightEyeScaleConnectGrp')
    pm.parent('RightEyeJnt','RightEyeScaleJnt')
    pm.parent('RightEyeScaleConnectGrp','HeadJnt')
    #Left Leg
    Utils.KGM_DuplicateJnt("LeftAnkleJnt", "LeftAnkleScaleFixJnt")
    pm.group(em=1,n="LeftAnkleFKConnectGrp")
    pm.xform(os=1,piv=(0, 0, 0))
    pm.group(em=1,n="LeftAnkleIKConnectGrp")
    pm.xform(os=1,piv=(0, 0, 0))
    Utils.KGM_Aline("LeftAnkleScaleFixJnt", "LeftAnkleFKConnectGrp", "a")
    Utils.KGM_Aline("LeftAnkleScaleFixJnt", "LeftAnkleIKConnectGrp", "p")
    pm.parent('LeftAnkleIKConnectGrp','LeftAnkleFKConnectGrp')
    pm.parent('LeftAnkleFKConnectGrp','LeftAnkleScaleFixJnt')
    pm.parent('LeftAnkleScaleFixJnt','LeftLegDwArc3Jnt')
    pm.parent('LeftAnkleJnt','LeftAnkleIKConnectGrp')
    #Right Leg
    Utils.KGM_DuplicateJnt("RightAnkleJnt", "RightAnkleScaleFixJnt")
    pm.group(em=1,n="RightAnkleFKConnectGrp")
    pm.xform(os=1,piv=(0, 0, 0))
    pm.group(em=1,n="RightAnkleIKConnectGrp")
    pm.xform(os=1,piv=(0, 0, 0))
    Utils.KGM_Aline("RightAnkleScaleFixJnt", "RightAnkleFKConnectGrp", "a")
    Utils.KGM_Aline("RightAnkleScaleFixJnt", "RightAnkleIKConnectGrp", "p")
    pm.parent('RightAnkleFKConnectGrp','RightAnkleScaleFixJnt')
    pm.parent('RightAnkleIKConnectGrp','RightAnkleFKConnectGrp')
    pm.parent('RightAnkleScaleFixJnt','RightLegDwArc3Jnt')
    pm.parent('RightAnkleJnt','RightAnkleIKConnectGrp')
    #Left Arm
    Utils.KGM_DuplicateJnt("LeftWristJnt", "LeftWristScaleFixJnt")
    pm.group(em=1,n="LeftWristFKConnectGrp")
    pm.xform(os=1,piv=(0, 0, 0))
    pm.group(em=1,n="LeftWristIKConnectGrp")
    pm.xform(os=1,piv=(0, 0, 0))
    Utils.KGM_Aline("LeftWristScaleFixJnt", "LeftWristFKConnectGrp", "a")
    Utils.KGM_Aline("LeftWristScaleFixJnt", "LeftWristIKConnectGrp", "a")
    pm.parent('LeftWristIKConnectGrp','LeftWristFKConnectGrp')
    pm.parent('LeftWristFKConnectGrp','LeftWristScaleFixJnt')
    pm.parent('LeftWristScaleFixJnt','LeftArmDwArc3Jnt')
    pm.parent('LeftWristJnt','LeftWristIKConnectGrp')
    #Right Arm
    Utils.KGM_DuplicateJnt("RightWristJnt", "RightWristScaleFixJnt")
    pm.group(em=1,n="RightWristFKConnectGrp")
    pm.xform(os=1,piv=(0, 0, 0))
    pm.group(em=1,n="RightWristIKConnectGrp")
    pm.xform(os=1,piv=(0, 0, 0))
    Utils.KGM_Aline("RightWristScaleFixJnt", "RightWristFKConnectGrp", "a")
    Utils.KGM_Aline("RightWristScaleFixJnt", "RightWristIKConnectGrp", "a")
    pm.parent('RightWristIKConnectGrp','RightWristFKConnectGrp')
    pm.parent('RightWristFKConnectGrp','RightWristScaleFixJnt')
    pm.parent('RightWristScaleFixJnt','RightArmDwArc3Jnt')
    pm.parent('RightWristJnt','RightWristIKConnectGrp')
    #oral
    pm.group(em=1,n="JawScaleConnectGrp")
    pm.xform(os=1,piv=(0, 0, 0))
    pm.group(em=1,n="LowerTeethScaleConnectGrp")
    pm.xform(os=1,piv=(0, 0, 0))
    pm.group(em=1,n="UpperTeethScaleConnectGrp")
    pm.xform(os=1,piv=(0, 0, 0))
    Utils.KGM_Aline("JawJnt", "JawScaleConnectGrp", "a")
    Utils.KGM_Aline("LowerTeethJnt", "LowerTeethScaleConnectGrp", "a")
    Utils.KGM_Aline("UpperTeethJnt", "UpperTeethScaleConnectGrp", "a")
    pm.parent('JawJnt','JawScaleConnectGrp')
    pm.parent('JawScaleConnectGrp','HeadJnt')
    pm.parent('LowerTeethJnt','LowerTeethScaleConnectGrp')
    pm.parent('LowerTeethScaleConnectGrp','JawJnt')
    pm.parent('UpperTeethJnt','UpperTeethScaleConnectGrp')
    pm.parent('UpperTeethScaleConnectGrp','HeadJnt')
    #Tongue
    pm.group(em=1,n="TongueJntScaleGrp")
    pm.xform(os=1,piv=(0, 0, 0))
    Utils.KGM_Aline("Tongue1Jnt", "TongueJntScaleGrp", "p")
    pm.parent('Tongue1Jnt','TongueJntScaleGrp')
    pm.parent('TongueJntScaleGrp','JawJnt')
    
    # Rebulid Grp
    pm.group(em=1,n="ChName")
    pm.group(em=1,n="ModGrp")
    pm.group(em=1,n="Head")
    pm.group(em=1,n="Body")
    pm.group(em=1,n="RigGrp")
    pm.parent('Head','ModGrp')
    pm.parent('Body','ModGrp')
    pm.parent('ModGrp','ChName')
    pm.parent('RigGrp','ChName')